// JavaScript Document
que1=[{ans:1,que:'「全球資訊網{ans:WWW)」的英文為何？',ans1:'World Wide Web',ans2:'Web Wide World',ans3:'Web World Wide',ans4:'World Web Wide'},
{ans:1,que:'「超文字傳輸協定」的英文簡稱為何？',ans1:'HTTP',ans2:'WWW',ans3:'URL',ans4:'TANET'},
{ans:4,que:'「檔案搜尋服務系統」的英文簡稱為何？',ans1:'FTP',ans2:'E-mail',ans3:'Telnet',ans4:'Archie'},
{ans:2,que:'「內容服務供應商」的英文簡稱為何？',ans1:'ISP',ans2:'ICP',ans3:'ERP',ans4:'LISP'},
{ans:2,que:'「中央處理單元」的英文簡稱為何？',ans1:'I/O',ans2:'CPU',ans3:'CCD',ans4:'UPS'},
{ans:2,que:'「全球資源定位法」的英文簡稱為何？',ans1:'WWW',ans2:'URL',ans3:'HTTP',ans4:'FTP'},
{ans:2,que:'「動態伺服器網頁」的英文簡稱為何？',ans1:'CGI',ans2:'ASP',ans3:'HTML',ans4:'DHTML'},
{ans:3,que:'「決策支援系統」的英文簡稱為何？',ans1:'DBMS',ans2:'DASD',ans3:'DSS',ans4:'IMS'},
{ans:3,que:'「個人數位助理」的英文簡稱為何？',ans1:'DBMS',ans2:'DB',ans3:'PDA',ans4:'DVD'},
{ans:4,que:'「動態主機配置協定」允許IP 位址自動配置，其英文簡稱為何？',ans1:'WWW',ans2:'TCP/IP',ans3:'POP',ans4:'DHCP'},
{ans:1,que:'「資料庫管理系統」的英文簡稱為何？',ans1:'DBMS',ans2:'PDA',ans3:'DB',ans4:'DVD'},
{ans:4,que:'「電子郵件」的英文簡稱為何？',ans1:'C-Mail',ans2:'A-Mail',ans3:'B-mail',ans4:'E-mail'},
{ans:3,que:'「企業內部網路」的英文為何？',ans1:'Telnet',ans2:'Extranet',ans3:'Intranet',ans4:'Internet'},
{ans:4,que:'「纜線數據機」的英文為何？',ans1:'Router',ans2:'ADSL',ans3:'Firewall',ans4:'Cable Modem'},
{ans:3,que:'「非對稱數位用戶線路」的英文簡稱為何？',ans1:'AOL',ans2:'ASP',ans3:'ADSL',ans4:'ATM'},
{ans:2,que:'「網域名稱伺服器」的英文簡稱為何？',ans1:'ISDN',ans2:'DNS',ans3:'ISP',ans4:'TCP'},
{ans:2,que:'「MIS」為何者的英文簡稱？',ans1:'決策支援系統',ans2:'管理資訊系統',ans3:'資料庫管理系統',ans4:'辦公室自動化'},
{ans:2,que:'「ISDN」為何者的英文簡稱？',ans1:'廣域網路',ans2:'整體服務數位網路',ans3:'區域網路',ans4:'加值型網路'},
{ans:3,que:'「LAN」為何者的英文簡稱？',ans1:'廣域網路',ans2:'整體服務數位網路',ans3:'區域網路',ans4:'加值型網路'},
{ans:2,que:'「MAN」為何者的英文簡稱？',ans1:'廣域網路',ans2:'都會網路',ans3:'區域網路',ans4:'加值型網路'},
{ans:1,que:'「WAN」為何者的英文簡稱？',ans1:'廣域網路',ans2:'整體服務數位網路',ans3:'區域網路',ans4:'加值型網路'},
{ans:3,que:'「電子佈告欄」的英文簡稱為何？',ans1:'FTP',ans2:'ISP',ans3:'BBS',ans4:'Archie'},
{ans:1,que:'電子商務中的「B2B」英文為何？',ans1:'Business to Business',ans2:'Business to Boss',ans3:'Boss to Business',ans4:'Boss to Boss'},
{ans:4,que:'「消費者與消費者」之間的電子商務關係，其英文簡稱為何？',ans1:'B2B',ans2:'C2B',ans3:'B2C',ans4:'C2C'},
{ans:3,que:'「企業者與消費者」之間的電子商務關係，其英文簡稱為何？',ans1:'B to B',ans2:'C to C',ans3:'B to C',ans4:'C to B'},
{ans:2,que:'在「校園網路的實習商城」中，廠商提供多樣的購書選擇，使學生可以自行上網訂購書籍，此一交易模式係屬於「電子商務」中的何種模式？',ans1:'C2C',ans2:'B2C',ans3:'C2B',ans4:'B2B'},
{ans:1,que:'電子商務中所提到的「C to B」，其英文為何？',ans1:'Consumer to Business',ans2:'Consumer to Boss',ans3:'Commerce to Business',ans4:'Commerce to Boss'},
{ans:4,que:'網路商場中，當廠商收到客戶的訂單後，系統將自動對其上游供應商的訂貨系統下訂單，則該兩廠商系統間的交易模式係屬於「電子商務」中的何種模式？',ans1:'C to C',ans2:'B to C',ans3:'C to B',ans4:'B to B'},
{ans:2,que:'使用電腦網路來做產品廣告行銷、網路訂購、付款等工作稱之為何？',ans1:'視訊會議',ans2:'電子商務',ans3:'虛擬實境',ans4:'電子佈告欄'},
{ans:3,que:'透過Internet 連線到網站購買電腦，這是使用網際網路上的何種服務？',ans1:'視訊會議',ans2:'虛擬實境',ans3:'網路購物',ans4:'電子佈告欄'},
{ans:4,que:'在「電子商務」中，廠商或業界經常採用的銷售管道為何？',ans1:'Telnet',ans2:'Extranet',ans3:'Intranet',ans4:'Internet'},
{ans:3,que:'何者屬於「企業單位」的網域名稱？',ans1:'.edu',ans2:'.gov',ans3:'.com',ans4:'.org'},
{ans:2,que:'何者屬於「政府機構」的網域名稱？',ans1:'.edu',ans2:'.gov',ans3:'.com',ans4:'.org'},
{ans:1,que:'何者屬於「教育單位」的網域名稱？',ans1:'.edu',ans2:'.gov',ans3:'.com',ans4:'.org'},
{ans:2,que:'何者屬於「個人」的網域名稱？',ans1:'.edu',ans2:'.idv',ans3:'.com',ans4:'.org'},
{ans:4,que:'何者屬於「組織單位或財團法人」的網域名稱？',ans1:'.edu',ans2:'.idv',ans3:'.com',ans4:'.org'},
{ans:4,que:'何者為「臺灣」的網域名稱？',ans1:'.jp',ans2:'.cn',ans3:'.hk',ans4:'.tw'},
{ans:3,que:'關於「網域名稱」之敘述何者錯誤？',ans1:'gov 為政府機構',ans2:'edu 為教育機構',ans3:'org 為商業機構',ans4:'mil 為軍方單位'},
{ans:4,que:'負責臺灣網域名稱{ans:Do main Name)管理的單位為何？',ans1:'國防部',ans2:'內政部',ans3:'新聞部',ans4:'TWNIC'},
{ans:1,que:'若以網址http://www.evta.gov.tw/index.html 為例，其中的「index.html」表示為何？',ans1:'網頁名稱',ans2:'檔案目錄名稱',ans3:'協定種類名稱',ans4:'伺服器網路位址'},
{ans:3,que:'若以網址http://www.evta.gov.tw/index.html 為例，其中的「http」表示為何？',ans1:'網頁名稱',ans2:'檔案目錄名稱',ans3:'協定種類名稱',ans4:'伺服器網路位址'},
{ans:4,que:'若以網址http://www.evta.gov.tw/index.html 為例，其中的「www.evta.gov.tw」表示為何？',ans1:'網頁名稱',ans2:'檔案目錄名稱',ans3:'協定種類名稱',ans4:'伺服器網域名稱'},
{ans:4,que:'若欲利用Internet Explorer 瀏覽器去瀏覽「網址為www.evta.gov.tw」且「埠號{ans:Port)為6000」之Web 虛擬主機，則請問如何輸入其位址？',ans1:'http://www.evta.gov.tw/',ans2:'http://www.evta.gov.tw/default.htm',ans3:'http://www.evta.gov.tw/6000',ans4:'http://www.evta.gov.tw:6000/'},
{ans:3,que:'網站的網址為http://www.amis.idv.tw，通常表示該網站是屬於何種網站？',ans1:'教育網站',ans2:'色情網站',ans3:'個人網站',ans4:'電台網站'},
{ans:4,que:'以網址http://www.ntnu.edu.tw/為例，那一項代表國家或地理區域？',ans1:'www',ans2:'ntnu',ans3:'edu',ans4:'tw'},
{ans:4,que:'關於URL 表示法何者錯誤？',ans1:'mms://www.labor.gov.tw/labor.wma',ans2:'https://nol.ntu.edu.tw',ans3:'ftp://ftp.labor.gov.tw',ans4:'bbs://www.labor.gov.tw/'},
{ans:1,que:'目前網際網路協定使用的IPv4 位址是由幾個位元組{ans:Byte)所組成？',ans1:'4',ans2:'8',ans3:'16',ans4:'32'},
{ans:3,que:'目前網際網路上所使用的IP 位址（IPv4），是由幾個位元（bit）所組成的？',ans1:'4',ans2:'6',ans3:'32',ans4:'64'},
{ans:3,que:'IP 位址為255.255.255.0 其功用為何？',ans1:'自我迴路測試',ans2:'廣播信號',ans3:'網路遮罩',ans4:'通訊閘位址'},
{ans:2,que:'目前網際網路的主要IP 協定{ans:Internet Protocol)是那ㄧ個版本？',ans1:'3',ans2:'4',ans3:'5',ans4:'6'},
{ans:4,que:'未來網際網路的下一個IP 協定{ans:Internet Protocol)是那ㄧ個版本，它將解決目前IP 不足的問題？',ans1:'2',ans2:'4',ans3:'5',ans4:'6'},
{ans:3,que:'使用IPv6 來解決IP 位址不足之問題，請問其使用幾個位元來定址？',ans1:'32',ans2:'64',ans3:'128',ans4:'256'},
{ans:4,que:'何者IP 位址不屬於私有位址{ans:Private Address)，供內部網路來使用？',ans1:'10.0.0.1',ans2:'172.16.0.1',ans3:'192.168.0.1',ans4:'127.0.0.1'},
{ans:2,que:'一個網際網路的IP 位址為140.*.*.*，它是屬於那一類級位址？',ans1:'A',ans2:'B',ans3:'C',ans4:'D'},
{ans:3,que:'關於IPv4{ans:Internet Protocol Version 4)之敘述何者錯誤？',ans1:'區分為網路別碼與主機識別碼兩部分',ans2:'長度為32 個位元',ans3:'劃分為A、B、C、D 四個等級',ans4:'一台電腦允許擁有兩個IP'},
{ans:4,que:'屬於Class C 等級作為私用的IP 範圍為何？',ans1:'1.0.0.0~126.255.255.255',ans2:'10.0.0.0~10.255.255.255',ans3:'172.16.0.0~172.31.255.255',ans4:'192.168.0.0~192.168.255.255'},
{ans:1,que:'Class C 等級的IP 每一區組數量有多少？',ans1:'256',ans2:'512',ans3:'1024',ans4:'2048'},
{ans:2,que:'IP 屬於Class C 等級的網路遮罩為何？',ans1:'255.255.255.255',ans2:'255.255.255.0',ans3:'255.255.0.0',ans4:'255.0.0.0'},
{ans:4,que:'安裝Internet Information Services 之後，在瀏覽器的網址列上輸入那一個IP 位址，可測試IIS 是否運作正常？',ans1:'100.0.0.1',ans2:'107.0.0.1',ans3:'117.0.0.1',ans4:'127.0.0.1'},
{ans:4,que:'在網際網路上，將網路主機名稱（如：www.labor.gov.tw）翻譯成IP 位址的電腦設備為何？',ans1:'Proxy Server',ans2:'File Server',ans3:'Mail Server',ans4:'Domain Name Server'},
{ans:4,que:'IP 的每組數字是用那個符號將其隔開的？',ans1:'，',ans2:'：',ans3:'；',ans4:'．'},
{ans:1,que:'Internet 的IP 位址中，何者的表示法有誤？',ans1:'140.5.30.288',ans2:'210.71.84.1',ans3:'163.20.165.55',ans4:'200.200.200.200'},
{ans:2,que:'何者是以4 個位元組的二進制數字來識別Internet 上之主機位址的表示方法？',ans1:'TCP',ans2:'IP',ans3:'UTP',ans4:'SMTP'},
{ans:3,que:'「Internet」最初設計的目的為何？',ans1:'學術',ans2:'行政',ans3:'軍事',ans4:'醫療'},
{ans:1,que:'何者是目前國內最大的「學術性網際網路」服務機構？',ans1:'TANet',ans2:'HiNet',ans3:'SeedNet',ans4:'BitNet'},
{ans:1,que:'在一個區域網路中，主機利用一個實體IP，讓其他電腦以虛擬IP 對映，而可以通行於網際網路，該主機需具有何種服務或功能？',ans1:'NAT',ans2:'WWW',ans3:'FTP',ans4:'PROXY'},
{ans:4,que:'網站最常使用何種技術來記錄使用者的線上活動，以提供使用者個人化服務，或簡化連上網路的程式？',ans1:'App3lication',ans2:'Pipe',ans3:'Session',ans4:'Cookie'},
{ans:4,que:'1M 是2 的幾次方？',ans1:'5',ans2:'10',ans3:'15',ans4:'20'},
{ans:1,que:'十進位數20 轉換成十六進位後，其值為何？',ans1:'14',ans2:'15',ans3:'20',ans4:'21'},
{ans:1,que:'十進制數50.875 以二進位表示，其值為何？',ans1:'110010.111',ans2:'110010.110',ans3:'110100.111',ans4:'110100.110'},
{ans:2,que:'二進位數1011011111001110 以十六進位表示，其值為何？',ans1:'C7BE',ans2:'B7CE',ans3:'B9CE',ans4:'C8EF'},
{ans:4,que:'十六進位數A5 轉換為二進位後，其值為何？',ans1:'10111001',ans2:'10110101',ans3:'10101000',ans4:'10100101'},
{ans:3,que:'何者最不可能是二進位數？',ans1:'101',ans2:'10',ans3:'1A',ans4:'11001'},
{ans:2,que:'二進位數值11000101 之2 的補數為何？',ans1:'11001010',ans2:'00111011',ans3:'00110101',ans4:'00111010'},
{ans:2,que:'二進位數值11001101 之1 的補數為何？',ans1:'11000010',ans2:'00110010',ans3:'00110011',ans4:'000110010'},
{ans:3,que:'若一年以365 日計算，至少需使用多少位元才可表示該數目？',ans1:'7',ans2:'8',ans3:'9',ans4:'10'},
{ans:3,que:'英文字母「B」的十進位ASCII 值為66，則字母「L」的十進位ASCII 值為何？',ans1:'74',ans2:'75',ans3:'76',ans4:'77'},
{ans:2,que:'在ASCII Code 的表示法中，何者不是依照字元其內碼大小順序排列？',ans1:'c＞b＞a',ans2:'A＞B＞C',ans3:'3＞2＞1',ans4:'p＞g＞e'},
{ans:3,que:'個人電腦通常採用ASCII 碼作為內部資料處理或數據傳輸方面的交換碼，其編碼方式為何？',ans1:'5 位元二進位碼',ans2:'6 位元二進位碼',ans3:'7 位元二進位碼',ans4:'9 位元二進位碼'},
{ans:2,que:'以ASCII Code 來儲存字串administrator，不包含引號，至少佔用記憶體多少位元組？',ans1:'9',ans2:'13',ans3:'18',ans4:'25'},
{ans:4,que:'關於編碼之敘述何者錯誤？',ans1:'「非壓縮{ans:Unpacked)的BCD 碼」係使用一組4 位元來表示一個十進位制的數字',ans2:'「通用漢字標準交換碼」為目前我國之國家標準交換碼',ans3:'「ASCII 碼」為常用的文數字資料的編碼',ans4:'「BIG-5碼」是中文的外碼'},
{ans:2,que:'以BIG-5 Code 來儲存字串電子化政府，不包含引號，共需使用記憶體多少位元組？',ans1:'7',ans2:'10',ans3:'11',ans4:'12'},
{ans:3,que:'何種內碼可以涵蓋世界各種不同的文字？',ans1:'ASCII 碼',ans2:'BIG-5 碼',ans3:'UNICODE 碼',ans4:'EBCDIC 碼'},
{ans:4,que:'同位檢查{ans:Parity Ckecking)是一項資料錯誤檢查的技術，何者不具有偶同位性？',ans1:'110011110',ans2:'101110101',ans3:'010101001',ans4:'011110100'},
{ans:1,que:'二進位編碼所組成的資料在運用時，通常會加一個bit，用來檢查資料是否正確，此bit 稱之為何？',ans1:'paritybit',ans2:'extendedbit',ans3:'signbit',ans4:'redundancybit'},
{ans:2,que:'若利用8bit 來表達整數型態資料，且最左位元0 代表正數，1 代表負數，負數與正數間互為2 的補數，則可表示之範圍為何？',ans1:'0～255',ans2:'-128～127',ans3:'-127～127',ans4:'-128～128'},
{ans:4,que:'電腦內部用何種方法表示負的整數？',ans1:'16 的補數表示法',ans2:'10 的補數表示法',ans3:'8 的補數表示法',ans4:'2 的補數表示法'},
{ans:3,que:'電腦處理小數問題時是採取何種方法自動調整小數點的位置？',ans1:'小數',ans2:'標準',ans3:'浮點',ans4:'一般標記法'},
{ans:1,que:'一個邏輯閘，若有任一輸入為1 時，其輸出即為0，此為何種邏輯閘？',ans1:'NOR 閘',ans2:'AND 閘',ans3:'XOR 閘',ans4:'OR 閘'},
{ans:2,que:'二進位數00100011 和11111100 做邏輯AND 運算結果，表示成十進位為何？',ans1:'3',ans2:'32',ans3:'35',ans4:'220'},
{ans:1,que:'計算機使用的二進位運算法中，10111100、11000011 的互斥或{ans:XOR)結果應為何？',ans1:'01111111',ans2:'00001111',ans3:'10000000',ans4:'11111111'},
{ans:1,que:'資料單位由小而大的排列順序為何？',ans1:'bit byte KB MB GB',ans2:'bit MB KB GB Byte',ans3:'bit GB byte KB MB',ans4:'bit byte MB GB KB'},
{ans:3,que:'一微秒{ans:Micro seconds)是幾分之幾秒？',ans1:'萬分之一秒',ans2:'十萬分之一秒',ans3:'百萬分之一秒',ans4:'千分之一秒'},
{ans:1,que:'「MIPS」為何者之衡量單位？',ans1:'CPU 之處理速度',ans2:'印表機之印字速度',ans3:'螢幕之解析度',ans4:'磁碟機之讀取速度'},
{ans:4,que:'「PPM{ans:Page Per Minute)」為何者之衡量單位？',ans1:'磁碟機讀取速度',ans2:'CPU 的處理速度',ans3:'螢幕的解析度',ans4:'印表機的列印速度'},
{ans:4,que:'網路資料的傳輸速度之單位為何？',ans1:'bpi',ans2:'cpi',ans3:'cps',ans4:'bps'},
{ans:1,que:'第一代電腦使用的元件為何？',ans1:'真空管',ans2:'電晶體',ans3:'積體電路',ans4:'超大型積體電路'},
{ans:3,que:'何者為計算機的心臟，由控制單元與算術邏輯單元所組成？',ans1:'ALU',ans2:'CU',ans3:'CPU',ans4:'Register'},
{ans:2,que:'何者不是電腦使用的匯流排？',ans1:'位址匯流排',ans2:'程式匯流排',ans3:'資料匯流排',ans4:'控制匯流排'},
{ans:3,que:'所謂32 位元個人電腦之32 位元是指CPU 的何者為32 位元？',ans1:'控制匯流排',ans2:'位址匯流排',ans3:'資料匯流排',ans4:'輸入／輸出匯流排'},
{ans:3,que:'CPU 的位址線有16 條，最多可定址出多少實體記憶空間？',ans1:'16K',ans2:'16M',ans3:'64K',ans4:'64M'},
{ans:4,que:'何者不是週邊設備？',ans1:'印表機',ans2:'CD-ROM',ans3:'鍵盤',ans4:'中央處理機'},
{ans:1,que:'何種記憶體內建於中央處理器{ans:CPU)內，做為CPU 暫存資料，以提升電腦的效能？',ans1:'快取記憶體{ans:Cache)',ans2:'快閃記憶體（Flash Memory）',ans3:'靜態隨機存取記憶體{ans:SRAM)',ans4:'動態隨機存取記憶體{ans:DRAM)'},
{ans:4,que:'資料在停電時不會立即消失的記憶體為何？',ans1:'揮發性記憶體',ans2:'靜態隨機存取記憶體{ans:SRAM)',ans3:'動態隨機存取記憶體{ans:DRAM)',ans4:'快閃記憶體{ans:Flash Memory)'},
{ans:2,que:'將軟體程式儲存於ROM，PROM 或EPROM 內的元件稱之為何？',ans1:'晶體',ans2:'韌體',ans3:'軟體',ans4:'硬體'},
{ans:3,que:'何種儲存媒體內的資料會隨電源中斷而消失？',ans1:'VCD',ans2:'ROM',ans3:'RAM',ans4:'DVD'},
{ans:4,que:'何者不是目前在PC 上常見的記憶體種類？',ans1:'DRAM',ans2:'DDR2',ans3:'FlashROM',ans4:'DROM'},
{ans:4,que:'具有32 條位址線的記憶體，其容量有多少？',ans1:'32KB',ans2:'32B',ans3:'16KB',ans4:'4GB'},
{ans:3,que:'電腦的記憶體容量為128KB，其可儲存的資料有多少位元組？',ans1:'128',ans2:'128000',ans3:'131072',ans4:'131000'},
{ans:3,que:'記憶體容量1474560Bytes 約等於多少？',ans1:'1.44KB',ans2:'144KB',ans3:'1.44MB',ans4:'1.44GB'},
{ans:2,que:'電源關掉後記憶體內容會隨著消失，即使再重新開機也無法再恢復其內容，此類記憶體稱之為何？',ans1:'ROM',ans2:'RAM',ans3:'EPROM',ans4:'PROM'},
{ans:1,que:'何種記憶體更新資料時不需使用燒錄器，而其寫入資料是以區塊為單位？',ans1:'Flash ROM',ans2:'PROM',ans3:'EEPROM',ans4:'Mask ROM'},
{ans:2,que:'記憶體讀取資料的速度何者最快？',ans1:'隨機存取記憶體{ans:RAM)',ans2:'L1 快取記憶體{ans:Cache Memory Level 1)',ans3:'L2 快取記憶體{ans:Cache Memory Level 2)',ans4:'快閃記憶體{ans:Flash Memory)'},
{ans:3,que:'記憶體讀取資料的速度何者最快？',ans1:'隨機存取記憶體{ans:RAM)',ans2:'唯讀光碟機{ans:DVD-ROM)',ans3:'快取記憶體{ans:Cache Memory)',ans4:'快閃記憶體{ans:Flash Memory)'},
{ans:2,que:'何種記憶體裝置存取資料的速度最快？',ans1:'唯讀記憶體',ans2:'快取記憶體',ans3:'隨機記憶體',ans4:'虛擬記憶體'},
{ans:3,que:'何者為輔助記憶體？',ans1:'BIOS',ans2:'RAM',ans3:'Disk',ans4:'ROM'},
{ans:3,que:'硬式磁碟每一面都由很多同心圓圈組成，這些圓圈稱之為何？',ans1:'磁頭{ans:Head)',ans2:'磁區{ans:Sector)',ans3:'磁軌{ans:Track)',ans4:'磁柱{ans:Cylinder)'},
{ans:3,que:'磁帶採用何種方式存取資料？',ans1:'索引存取',ans2:'直接存取',ans3:'循序存取',ans4:'隨機存取'},

{ans:4,que:'何者為循序存取{ans:Sequential Access)的輸出入媒體？',ans1:'可抽取式硬碟{ans:Hard Disk)',ans2:'光碟{ans:CD-ROM)',ans3:'磁片{ans:Floppy Disk)',ans4:'磁帶{ans:Tape)'},
{ans:3,que:'關於3.5 吋軟碟片的防寫缺口為打開狀態之敘述何者正確？',ans1:'無法使用',ans2:'無法讀出',ans3:'無法寫入',ans4:'只能寫入'},
{ans:3,que:'3.5 吋的磁碟片，其記憶體容量為何？',ans1:'360KB',ans2:'1.2MB',ans3:'1.44MB',ans4:'1.44GB'},
{ans:2,que:'磁片的基本儲存單位為何？',ans1:'磁柱',ans2:'磁區',ans3:'磁軌',ans4:'磁頭'},
{ans:4,que:'使用磁片最好固定時間用清潔液清洗何處？',ans1:'防寫槽',ans2:'中心孔',ans3:'讀寫孔',ans4:'磁頭'},
{ans:1,que:'何者是辨識磁軌存放資料的起始位置？',ans1:'索引孔',ans2:'讀寫槽',ans3:'轉軸孔',ans4:'防寫孔'},
{ans:3,que:'何者不是常用的記憶卡？',ans1:'MS 卡',ans2:'SD 卡',ans3:'NIC 卡',ans4:'MMC 卡'},
{ans:2,que:'利用光學原理製成的DVD-ROM 數位式影音光碟機，其單倍速為何？',ans1:'150KB/S',ans2:'1350KB/S',ans3:'18500KB/S',ans4:'300KB/S'},
{ans:2,que:'「數位影像唯讀光碟機」的英文簡稱為何？',ans1:'CD-ROM',ans2:'DVD-ROM',ans3:'LD-ROM',ans4:'EPROM'},
{ans:1,que:'一個50 倍速之CD-ROM 代表其讀取速度為50 乘以何者？',ans1:'150KB/S',ans2:'1350KB/S',ans3:'1850KB/S',ans4:'300KB/S'},
{ans:4,que:'何者為CD 音效的取樣頻率？',ans1:'11.025KHz',ans2:'22.05KHz',ans3:'33.75KHz',ans4:'44.1KHz'},
{ans:1,que:'何者不屬於光碟原理之儲存設備？',ans1:'ZIP',ans2:'CD-ROM',ans3:'DVD-ROM',ans4:'CD-R/W'},
{ans:1,que:'輔助記憶裝置中，何者存取速度最快？',ans1:'硬碟',ans2:'軟碟',ans3:'光碟',ans4:'磁帶'},
{ans:3,que:'何種記憶體裝置存取資料的速度最慢？',ans1:'硬碟',ans2:'光碟',ans3:'軟碟',ans4:'RAM'},
{ans:1,que:'兼具輸入及輸出功能的裝置為何？',ans1:'磁碟機',ans2:'列表機',ans3:'繪圖機',ans4:'滑鼠'},
{ans:4,que:'何者同時是輸入及輸出裝置？',ans1:'唯讀式光碟機',ans2:'數位板',ans3:'鍵盤',ans4:'隨身碟'},
{ans:3,que:'何種裝置只能做輸出設備使用，無法作輸入設備使用？',ans1:'觸摸式螢幕',ans2:'鍵盤',ans3:'印表機',ans4:'光筆'},
{ans:1,que:'何者為撞擊式的印表機？',ans1:'點陣印表機',ans2:'噴墨印表機',ans3:'雷射印表機',ans4:'繪圖機'},
{ans:1,que:'噴墨印表機列印圖片檔時，採用何種輸出解析度，列印出來的圖片會比較大？',ans1:'150dpi',ans2:'300dpi',ans3:'600dpi',ans4:'1200dpi'},
{ans:2,que:'個人電腦想要列印需要那一項設備？',ans1:'數據機',ans2:'印表機',ans3:'燒錄機',ans4:'掃瞄機'},
{ans:2,que:'印表機通常連接在主機的何處？',ans1:'Game Port',ans2:'LPT1 或USB',ans3:'COM2',ans4:'COM1'},
{ans:2,que:'若印表機的列印密度為360dpi，其代表的意義為每一什麼單位可列印360 點數？',ans1:'公尺',ans2:'英吋',ans3:'英呎',ans4:'公分'},
{ans:1,que:'鍵盤是屬於那類設備？',ans1:'輸入設備',ans2:'輸入媒體',ans3:'輸出設備',ans4:'輸出媒體'},
{ans:1,que:'螢幕的輸出品質取決於那項標準？',ans1:'解析度',ans2:'輸出速度',ans3:'重量',ans4:'大小'},
{ans:3,que:'何者是計算螢幕{ans:顯示器)對角線尺寸的向度？',ans1:'寬度',ans2:'厚度',ans3:'長度',ans4:'深度'},
{ans:1,que:'何者僅能做輸入裝置？',ans1:'讀卡機',ans2:'磁碟機',ans3:'螢幕',ans4:'列表機'},
{ans:3,que:'能閱讀銀行支票上金額的輸入裝置為何？',ans1:'BCR',ans2:'OMR',ans3:'MICR',ans4:'POS'},
{ans:3,que:'商品包裝上所貼的條碼{ans:Bar Code)是協助結帳及庫存盤點之用，該條碼在此方面的資料處理作業上是屬於那類？',ans1:'輸出畫面',ans2:'輸出設備',ans3:'輸入媒體',ans4:'輸出媒體'},
{ans:1,que:'條碼閱讀機屬於那類設備？',ans1:'輸入設備',ans2:'輸出設備',ans3:'儲存設備',ans4:'保密設備'},
{ans:4,que:'在安裝介面卡時，若PC 內已有其他介面卡存在，則應該注意I/O 位址、IRQ、以及何者是否相衝突？',ans1:'BaudRate',ans2:'Fra 2000 Size',ans3:'Packet Size',ans4:'DMA'},
{ans:1,que:'PS2 介面接腳可用於連接滑鼠及鍵盤，其接腳為幾PIN？',ans1:'6',ans2:'7',ans3:'8',ans4:'9'},
{ans:4,que:'RS-232C 是屬於那類介面？',ans1:'圖形介面',ans2:'顯示介面',ans3:'並列式介面',ans4:'串列式介面'},
{ans:2,que:'何者可用來將數位訊號轉換成類比訊號？',ans1:'掃瞄器',ans2:'數據機',ans3:'印表機',ans4:'數位相機'},
{ans:1,que:'PC 系統中的滑鼠、數據機{ans:Modem)等週邊裝置，大多以何種介面連接到主機上？',ans1:'RS-232',ans2:'RS-422',ans3:'10Base-T',ans4:'Centronic'},
{ans:3,que:'連接主機與週邊的介面卡需插於何處？',ans1:'CPU',ans2:'電源',ans3:'擴充槽',ans4:'記憶單元'},
{ans:1,que:'個人電腦想要上網需要那一項設備？',ans1:'數據機',ans2:'印表機',ans3:'燒錄機',ans4:'掃瞄機'},
{ans:1,que:'關於網路傳輸媒體，何種線材其資料傳輸的速度最快？',ans1:'光纖',ans2:'雙絞線',ans3:'同軸電纜',ans4:'電話線'},
{ans:3,que:'同軸電纜線使用什麼編號來分級？',ans1:'NG-58',ans2:'PG-58',ans3:'RG-58',ans4:'YG-58'},
{ans:3,que:'無遮蔽雙絞線使用類似電話電纜所用的接頭來附加到電腦上，此接頭稱之為何？',ans1:'MJ-45',ans2:'PJ-45',ans3:'RJ-45',ans4:'WJ-45'},
{ans:2,que:'RJ-45 腳位在乙太網路100 BASE-T Category 5 UTP 纜線中傳送和接收資料被使用的有1 和2 線，以及那二條線？',ans1:'3 和4',ans2:'3 和6',ans3:'4 和5',ans4:'7 和8'},
{ans:3,que:'大量資料能以光速在極細的玻璃纖維中傳送的是那一種媒介？',ans1:'同軸電纜',ans2:'微波',ans3:'光纖電纜',ans4:'數據機'},
{ans:2,que:'彙集星狀網路上各節點的裝備稱之為何？',ans1:'伺服器',ans2:'集線器',ans3:'路由器',ans4:'橋接器'},
{ans:4,que:'何者不是網路連線設備？',ans1:'數據機',ans2:'路由器',ans3:'橋接器',ans4:'掃瞄器'},
{ans:2,que:'集線器{ans:Hub)的網路接線屬於那類型的網路？',ans1:'環狀型{ans:Ring)',ans2:'星狀型{ans:Star)',ans3:'直線型',ans4:'曲線型{ans:Curve)'},
{ans:2,que:'何者不是常見的網路架構？',ans1:'環狀網路',ans2:'球狀網路',ans3:'星狀網路',ans4:'匯流排狀網路'},
{ans:3,que:'網際網路的網路拓樸為何？',ans1:'匯流排網路',ans2:'星狀網路',ans3:'網狀網路',ans4:'環狀網路'},
{ans:2,que:'何者不屬於區域網路的標準？',ans1:'TokenRing',ans2:'HiNet',ans3:'ARCnet',ans4:'Ethernet'},
{ans:3,que:'以56Kbps 的數據機{ans:Modem)撥接上網，下載140Kbytes 大小的資料，理論上約需多少時間？',ans1:'0.4 秒',ans2:'2.5 秒',ans3:'20 秒',ans4:'20 分'},
{ans:1,que:'何者不屬於「寬頻」上網？',ans1:'56K 數據機撥接上網',ans2:'ADSL',ans3:'Cable Modem',ans4:'申請T1 專線'},
{ans:3,que:'何者負責將封包從電腦傳到網路上，並協調傳輸的速度和封包大小，以確保資料能正確的傳到目的地？',ans1:'CP6U',ans2:'RAM',ans3:'網路卡',ans4:'印表機'},
{ans:3,que:'個人電腦透過電話線通訊時，需配合那一種設備？',ans1:'前端機{ans:Front-end)',ans2:'多工機{ans:Multiplexer)',ans3:'數據機{ans:Modem)',ans4:'集訊機{ans:Concentrator)'},
{ans:4,que:'高速乙太網路{ans:FastEthernet)最高傳輸的速度為何？',ans1:'2MBps',ans2:'10MBps',ans3:'16MBps',ans4:'100MBps'},
{ans:4,que:'何者不是優質的網路規劃條件？',ans1:'不須多費工夫就能連上網',ans2:'有輕微的故障發生時，網路也不會中斷',ans3:'具有必要的安全措施',ans4:'超高的成本'},
{ans:2,que:'根據TIA/EIA 商業電信水平佈線標準，從集線器到任何工作站間的無遮蔽雙絞線{ans:UTP)最遠距離須在多少公尺以內？',ans1:'50',ans2:'100',ans3:'150',ans4:'200'},
{ans:3,que:'電腦網路介面卡{ans:NIC)的最主要功能為何？',ans1:'偵測電腦病毒',ans2:'監測網路狀況',ans3:'電腦主機資訊與網路訊號間的轉換',ans4:'防止駭客入侵'},
{ans:2,que:'某乙太網路卡的實體位置{ans:Physical Address)為00-14-2A-2D-A6-F9，則它的網路卡製造商的代碼為何？',ans1:'00-14',ans2:'00-14-2A',ans3:'00-14-2A-2D',ans4:'00-14-2A-2D-A6'},
{ans:4,que:'何種網路媒介的傳輸距離最遠？',ans1:'同軸電纜',ans2:'雙絞線',ans3:'多模光纖',ans4:'單模光纖'},
{ans:3,que:'藍芽{ans:Blue tooth)無線傳輸技術是使用那一個頻道？',ans1:'1.8GHz',ans2:'1.9GHz',ans3:'2.4GHz',ans4:'3GHz'},
{ans:1,que:'何者對電腦的通訊效率影響最低？',ans1:'顯示卡處理速率',ans2:'網路介面卡速率',ans3:'主記憶體存取速率',ans4:'主機板匯流排速率'},
{ans:3,que:'網際網路涵蓋的範圍是屬於那類型的網路？',ans1:'區域網路',ans2:'校園網路',ans3:'廣域網路',ans4:'都會網路'},
{ans:2,que:'網際網路上提供各式各樣服務的電腦主機稱之為何？',ans1:'PC',ans2:'Sever',ans3:'Workstation',ans4:'NoteBook'},
{ans:3,que:'關於網路的敘述何者錯誤？',ans1:'E-mail 可用以傳遞文字、影像、聲音等以電子信號儲存的檔案',ans2:'TCP/IP 是目前Internet 網際網路普遍採用的通訊協定',ans3:'URL 是一種電腦網路的連接架構',ans4:'TANet 是台灣學術網路'},
{ans:4,que:'何者為一般無線網路上網的加密技術？',ans1:'SSL',ans2:'HTTPs',ans3:'Encode',ans4:'WEP'},
{ans:4,que:'何者並非網際網路（Internet）所提供之服務？',ans1:'E-mail',ans2:'WWW',ans3:'BBS',ans4:'UPS'},
{ans:4,que:'何者係利用家用電話線路作為資料傳遞的媒介，其上傳與下傳資料之速度並不相等？',ans1:'Cabel Modem',ans2:'ISDN',ans3:'ATM',ans4:'ADSL'},
{ans:4,que:'ADSL 寬頻網路傳輸速率為2M/512K，上傳2MB 的圖檔，約需多少秒？',ans1:'1',ans2:'4',ans3:'16',ans4:'32'},
{ans:4,que:'ADSL 寬頻網路傳輸速率為2M/512K，下載4MB 的音樂檔，約需多少秒？',ans1:'2',ans2:'4',ans3:'8',ans4:'16'},
{ans:2,que:'個人電腦透過ADSL 寬頻連上Internet 時，何種設備在家中不需用到？',ans1:'電話線',ans2:'Router',ans3:'數據機',ans4:'電腦'},
{ans:3,que:'關於ADSL 敘述何者錯誤？',ans1:'中文稱為非對稱數位用戶線路',ans2:'使用電話線做傳輸媒介',ans3:'無法同時上網及講電話',ans4:'上傳及下載資料時的傳輸速率不對稱'},
{ans:2,que:'何者是利用有線電視的頻道做為資料傳輸的媒介？',ans1:'ATM',ans2:'Cable Modem',ans3:'ADSL',ans4:'ISDN'},
{ans:3,que:'網際網路{ans:Internet)是藉由何種技術來完成資料交換？',ans1:'電路交換',ans2:'數位整合交換',ans3:'分封交換',ans4:'訊息交換'},
{ans:2,que:'有關網路之敘述何者錯誤？',ans1:'廣域網路之範圍較區域網路為大',ans2:'中繼器可用來串接兩個不同的網路',ans3:'一般家庭用戶大部分是利用數據機連上ISP',ans4:'Telnet 是Internet 提供的一種服務'},
{ans:2,que:'何種設備可連接兩個（或以上）的TCP/IP 網路，並具有路徑選擇的能力?',ans1:'Bridge',ans2:'Router',ans3:'Hub',ans4:'Switch'},
{ans:2,que:'MODEM 之功能為何？',ans1:'轉換ASCII 碼與EBCDIC 碼',ans2:'轉換類比與數位訊號',ans3:'轉換內碼與外碼',ans4:'轉換原始碼與目的碼'},
{ans:3,que:'使用Category 5 的UTP 纜線，可用於100 Mbps 的乙太網路傳輸，其內部絞線共幾對？',ans1:'2',ans2:'3',ans3:'4',ans4:'5'},
{ans:2,que:'在10 BASE T 架構中從HUB 到工作站最大傳送距離是多少公尺？',ans1:'50',ans2:'100',ans3:'185',ans4:'500'},
{ans:4,que:'乙太網路中，使用10 BASE T 規格的纜線時，它必須採用那一種標準接頭？',ans1:'AUI',ans2:'BNC',ans3:'RJ-11',ans4:'RJ-45'},
{ans:4,que:'乙太網路的傳輸速度在100Mbps 以內時，則需採用那一種等級的UTP 纜線？',ans1:'Cat.2',ans2:'Cat.3',ans3:'Cat.4',ans4:'Cat.5'},
{ans:1,que:'無線寬頻網路卡之制定標準為何？',ans1:'IEEE 802.11',ans2:'IEEE 802.12',ans3:'IEEE 802.13',ans4:'IEEE 802.14'},
{ans:2,que:'那一個無線網路標準運作在5GHz 傳送範圍且有54Mbps 的資料傳送率？',ans1:'802.11',ans2:'802.11a',ans3:'802.11b',ans4:'802.11g'},
{ans:3,que:'欲將有線的區域網路轉換成無線的乙太區域網路，何者必須改變？',ans1:'不需要作任何改變',ans2:'每台主機將需要新的IP 位址',ans3:'每台主機將需要適當的網路卡或轉接器',ans4:'每台主機將需要升級作業系統'},
{ans:3,que:'何種網路傳輸媒體的訊號在超過100 公尺需再生{ans:Repeat)？',ans1:'10 BASE 2',ans2:'10 BASE 5',ans3:'100 BASE-T',ans4:'100 BASEFX'},
{ans:4,que:'乙太網路網段的CSMA/CD 在碰撞發生後，如何管理訊框的重傳？',ans1:'偵測到碰撞的第一個設備有重傳的優先權',ans2:'具較低MAC 位址的設備決定重傳的優先權',ans3:'網路上的設備舉行選舉以決定重傳資料的優先權',ans4:'當碰撞發生時在傳送的設備沒有重傳的優先權'},
{ans:4,que:'網路卡上的MAC 位址是屬於OSI 模式的那一層?',ans1:'實體層',ans2:'應用層',ans3:'網路層',ans4:'資料鏈結層'},
{ans:3,que:'MAC 位址來源在那裡？',ans1:'DHCP 伺服器資料庫',ans2:'由管理者組態設定',ans3:'燒在網路卡的ROM',ans4:'在電腦上的網路組態'},
{ans:3,que:'1000 BASE-T 如何使用UTP 線對來完成傳輸?',ans1:'兩對線用來傳送，且兩對線用來接收',ans2:'一對線用來傳送，一對線用來接收，一對線用來作時脈，而一對線用來作錯誤更正',ans3:'所有四對線被兩台主機並行使用來同時傳輸和接收',ans4:'兩對線被如10 BASE-T 和1000 BASE-TX 一樣地使用'},
{ans:2,que:'數位傳輸方式中，所謂的「傳輸速率」為何？',ans1:'傳輸線的粗細',ans2:'速度每秒多少個位元{ans:bps)',ans3:'頻道的最高頻率和最低頻率的差',ans4:'網路卡的傳輸能力'},
{ans:3,que:'類比傳輸頻道中，所謂的「頻寬」為何？',ans1:'傳輸線的粗細',ans2:'速度每秒多少個位元{ans:bps)',ans3:'頻道的最高頻率和最低頻率的差',ans4:'網路卡的傳輸能力'},
{ans:3,que:'國際標準組織{ans:ISO)所制定的開放式系統連結{ans:OSI)參考模式中，何者與硬體最密切相關？',ans1:'資料鏈結層',ans2:'會議層',ans3:'實體層',ans4:'網路層'},
{ans:4,que:'國際標準組織{ans:ISO)所制定的開放式系統連結{ans:OSI)參考模式中，何者的主要功能是負責傳送路徑的選擇？',ans1:'資料鏈結層',ans2:'會議層',ans3:'實體層',ans4:'網路層'},
{ans:3,que:'國際標準組織{ans:ISO)所制定的開放式系統連結{ans:OSI)參考模式中，電子郵件{ans:E-mail)是通信協定那一層的功能？',ans1:'網路層',ans2:'實體層',ans3:'應用層',ans4:'交談層'},
{ans:3,que:'何種網路設備，其主要運作層次為OSI 七層中的「網路層」？',ans1:'網路卡{ans:NIC)',ans2:'橋接器{ans:bridge)',ans3:'路由器{ans:router)',ans4:'中繼器{ans:repeater)'},
{ans:2,que:'可將數位訊號與類比訊號作相互轉換的裝置為何？',ans1:'前端處理機{ans:Front-endprocessor)',ans2:'數據機{ans:Modem)',ans3:'通訊閘道{ans:Communication Channel)',ans4:'終端機{ans:Terminal)'},
{ans:3,que:'只能單向傳送資料的傳輸方法稱之為何？',ans1:'多工',ans2:'半雙工',ans3:'單工',ans4:'全雙工'},
{ans:4,que:'在不同時間可作雙向相傳輸，當某一方處於接收狀況時就不能傳送資料的方式稱之為何？',ans1:'區域網路{ans:LAN)',ans2:'單工{ans:Simplex)',ans3:'全雙工{ans:Duplex)',ans4:'半雙工{ans:Half-Duplex)'},
{ans:3,que:'在區域網路，一台工作站可同時傳送及接收資料，這是屬於何種方式的傳輸？',ans1:'混合式',ans2:'半雙工',ans3:'全雙工',ans4:'多工'},
{ans:4,que:'無線電視台將信號傳輸至家中電視機，這是屬於何種方式的傳輸？',ans1:'全雙工{ans:Full-duplex)',ans2:'半雙工{ans:Half-duplex)',ans3:'全多工{ans:Full-multiplexer)',ans4:'單工{ans:Simplex)'},
{ans:3,que:'以電腦創造出多媒體的立體空間稱之為何？',ans1:'創造實境',ans2:'電腦實境',ans3:'虛擬實境',ans4:'天外實境'},
{ans:3,que:'以數種媒體組合呈現資訊的方式稱之為何？',ans1:'單媒體',ans2:'雙媒體',ans3:'多媒體',ans4:'大媒體'},
{ans:1,que:'"熱插拔"就是可以在不關機的情況下，任意加入或拔出週邊設備，那種介面屬於"熱插拔"？',ans1:'USB 介面',ans2:'PCI介面',ans3:'ISA 介面',ans4:'AGP 介面'},
{ans:3,que:'那一個十六進位的RGB 顏色組合不是網頁安全顏色{ans:Web Safe Color)？',ans1:'#CC00FF',ans2:'#663399',ans3:'#BB00EE',ans4:'#9900CC'},
{ans:2,que:'在網際網路{ans:Internet)上，用什麼來識別電腦？',ans1:'URL',ans2:'IP Address',ans3:'computer ID',ans4:'computer name'},
{ans:4,que:'一部專門用來過濾內外部網路間通訊的電腦稱之為何？',ans1:'熱站',ans2:'疫苗',ans3:'冷站',ans4:'防火牆'},
{ans:1,que:'何者不是網路防火牆的建置區域？',ans1:'交通網路',ans2:'內部網路',ans3:'外部網路',ans4:'網際網路'},
{ans:4,que:'何者不是網路防火牆的管理功能？',ans1:'支援遠端管理',ans2:'存取控制',ans3:'日誌記錄',ans4:'價格管理'},
{ans:2,que:'那類伺服器提供網頁快取及防火牆的功能？',ans1:'FTP server',ans2:'Proxy server',ans3:'DHCP server',ans4:'Web server'}]