// JavaScript Document
que2=[{ans:4,que:'"Access"是屬於那類軟體？',ans1:'視訊編輯軟體',ans2:'文書編輯軟體',ans3:'圖形編輯軟體',ans4:'資料庫軟體'},
{ans:3,que:'"After Effects"是屬於那類軟體？',ans1:'系統軟體',ans2:'簡報軟體',ans3:'視訊編輯軟體',ans4:'文書編輯軟體'},
{ans:2,que:'"Kaspersky"是屬於那類軟體？',ans1:'系統軟體',ans2:'防毒軟體',ans3:'簡報軟體',ans4:'文書編輯軟體'},
{ans:3,que:'"AutoCAD"是屬於那類軟體？',ans1:'系統軟體',ans2:'簡報軟體',ans3:'製圖軟體',ans4:'資料庫軟體'},
{ans:2,que:'"CorelDraw"是屬於那類軟體？',ans1:'系統軟體',ans2:'美工繪圖軟體',ans3:'簡報軟體',ans4:'文書編輯軟體'},
{ans:2,que:'"WinZip"是屬於那類軟體？',ans1:'系統軟體',ans2:'壓縮及解壓縮工具軟體',ans3:'簡報軟體',ans4:'文書編輯軟體'},
{ans:2,que:'"Director"是屬於那類軟體？',ans1:'系統軟體',ans2:'多媒體軟體',ans3:'簡報軟體',ans4:'文書編輯軟體'},
{ans:2,que:'"Dreamweaver"是屬於那類軟體？',ans1:'系統軟體',ans2:'網頁設計軟體',ans3:'簡報軟體',ans4:'文書編輯軟體'},
{ans:3,que:'"Excel"是屬於那類軟體？',ans1:'系統軟體',ans2:'簡報軟體',ans3:'試算表軟體',ans4:'資料庫軟體'},
{ans:2,que:'"Premiere"是屬於那類軟體？',ans1:'系統軟體',ans2:'視訊編輯軟體',ans3:'簡報軟體',ans4:'文書編輯軟體'},
{ans:1,que:'"Flash"是屬於那類軟體？',ans1:'網頁動畫設計軟體',ans2:'文書編輯軟體',ans3:'簡報軟體',ans4:'資料庫軟體'},
{ans:2,que:'"FrontPage"是屬於那類軟體？',ans1:'彩繪軟體',ans2:'網頁設計軟體',ans3:'簡報軟體',ans4:'文書編輯軟體'},
{ans:2,que:'"Fusion"是屬於那類軟體？',ans1:'系統軟體',ans2:'網頁設計軟體',ans3:'簡報軟體',ans4:'文書編輯軟體'},
{ans:2,que:'"Illustrator"是屬於那類軟體？',ans1:'系統軟體',ans2:'繪圖影像軟體',ans3:'簡報軟體',ans4:'文書編輯軟體'},
{ans:2,que:'"Word"是屬於那類軟體？',ans1:'視訊編輯軟體',ans2:'文書編輯軟體',ans3:'圖形編輯軟體',ans4:'資料庫軟體'},
{ans:1,que:'"Maya"是屬於那類軟體？',ans1:'3D 視訊動畫工具軟體',ans2:'程式語言',ans3:'簡報軟體',ans4:'文書編輯軟體'},
{ans:1,que:'"Painter"是屬於那類軟體？',ans1:'彩繪軟體',ans2:'程式語言',ans3:'簡報軟體',ans4:'文書編輯軟體'},
{ans:2,que:'"PC-cillin"是屬於那類軟體？',ans1:'系統軟體',ans2:'防毒及掃毒軟體',ans3:'簡報軟體',ans4:'文書編輯軟體'},
{ans:2,que:'"PhotoDraw"是屬於那類軟體？',ans1:'系統軟體',ans2:'影像繪圖軟體',ans3:'簡報軟體',ans4:'文書編輯軟體'},
{ans:2,que:'"PhotoImpact"是屬於那類軟體？',ans1:'系統軟體',ans2:'影像處理軟體',ans3:'簡報軟體',ans4:'文書編輯軟體'},
{ans:3,que:'"Photoshop"是屬於那類軟體？',ans1:'視訊編輯軟體',ans2:'文書編輯軟體',ans3:'圖形編輯軟體',ans4:'資料庫軟體'},
{ans:2,que:'"PowerPoint"是屬於那類軟體？',ans1:'視訊編輯軟體',ans2:'簡報編輯軟體',ans3:'圖形編輯軟體',ans4:'資料庫軟體'},
{ans:3,que:'"Project"是屬於那類軟體？',ans1:'系統軟體',ans2:'簡報軟體',ans3:'專案管理軟體',ans4:'文書編輯軟體'},
{ans:2,que:'"QBasic"是屬於那類軟體？',ans1:'系統軟體',ans2:'程式語言',ans3:'簡報軟體',ans4:'文書編輯軟體'},
{ans:2,que:'"Delphi"是屬於那類軟體？',ans1:'系統軟體',ans2:'程式語言',ans3:'簡報軟體',ans4:'文書編輯軟體'},
{ans:2,que:'"Visual Basic"是屬於那類軟體？',ans1:'系統軟體',ans2:'程式語言',ans3:'簡報軟體',ans4:'資料庫軟體'},
{ans:3,que:'"Visual FoxPro"是屬於那類軟體？',ans1:'系統軟體',ans2:'簡報軟體',ans3:'程式語言',ans4:'文書編輯軟體'},
{ans:2,que:'"Visual InterDev"是屬於那類軟體？',ans1:'系統軟體',ans2:'程式語言',ans3:'簡報軟體',ans4:'文書編輯軟體'},
{ans:3,que:'"Visual J++"是屬於那類軟體？',ans1:'系統軟體',ans2:'簡報軟體',ans3:'程式語言',ans4:'文書編輯軟體'},
{ans:1,que:'"Java"是屬於那類軟體？',ans1:'系統軟體',ans2:'繪圖軟體',ans3:'簡報軟體',ans4:'文書編輯軟體'},
{ans:3,que:'Microsoft 的"Internet Explorer"是屬於那類軟體？',ans1:'掃瞄器',ans2:'伺服器',ans3:'瀏覽器',ans4:'作業系統'},
{ans:1,que:'何者是「製作動畫及透明圖」的應用軟體？',ans1:'Gif Animator',ans2:'Media Player',ans3:'Word',ans4:'Win RAR'},
{ans:1,que:'何者是「看圖及秀圖」的應用軟體？',ans1:'ACDSee',ans2:'WinZip',ans3:'WinRAR',ans4:'VBA'},
{ans:4,que:'何者不是「網頁製作」的應用軟體？',ans1:'Flash',ans2:'Dreamweaver',ans3:'SharePoint',ans4:'VBA'},
{ans:3,que:'何者不是「網頁製作」的應用軟體？',ans1:'Dreamweaver',ans2:'FrontPage',ans3:'Outlook',ans4:'Namo'},
{ans:2,que:'何者是「應用軟體」？',ans1:'Linux',ans2:'Word 2003',ans3:'Windows XP',ans4:'Unix'},
{ans:1,que:'英文名稱所對應之中文名稱何者錯誤？',ans1:'FTP「檔案搜尋系統」',ans2:'TANet「台灣學術網路」',ans3:'IRC「多人線上聊天系統」',ans4:'Telnet「遠端登入」'},
{ans:4,que:'中文名稱所對應之英文名稱何者錯誤？',ans1:'「檔案傳輸協定」FTP',ans2:'「電子佈告欄」BBS',ans3:'「電子郵件」E-mail',ans4:'「區域網路」WAN'},
{ans:3,que:'當播放串流媒體時，檔案會在播放之前先部分下載，並儲存在電腦緩衝區{ans:Buffer)中，此種處理方式稱為何？',ans1:'暫存處理',ans2:'及時處理',ans3:'緩衝處理',ans4:'平行處理'},
{ans:2,que:'何者是「網頁製作」所使用的語言？',ans1:'C',ans2:'HTML',ans3:'VB',ans4:'PASCAL'},
{ans:4,que:'何者是「全球資訊網{ans:World Wide Web)」使用最普遍的副檔名？',ans1:'.exe',ans2:'.com',ans3:'.sys',ans4:'.htm'},
{ans:1,que:'何者是「向量影像檔」的副檔名？',ans1:'.ai',ans2:'.tiff',ans3:'.gif',ans4:'.bmp'},
{ans:1,que:'何者是「影像播放檔」的副檔名？',ans1:'.avi',ans2:'.pdf',ans3:'.dbf',ans4:'.bmp'},
{ans:4,que:'何者不是「壓縮檔」的副檔名？',ans1:'.arj',ans2:'.zip',ans3:'.rar',ans4:'.bmp'},
{ans:3,que:'何者不是「音樂播放檔」的副檔名？',ans1:'.mp3',ans2:'.wav',ans3:'.jpg',ans4:'.mid'},
{ans:4,que:'何者不是「音樂音效檔」的副檔名？',ans1:'.au',ans2:'.mp3',ans3:'.ra',ans4:'.rar'},
{ans:3,que:'何者是「動態圖形」的副檔名？',ans1:'.cgm',ans2:'.bmp',ans3:'.gif',ans4:'.jpg'},
{ans:4,que:'何者是「PhotoImpact 12」預設存檔的副檔名？',ans1:'.gif',ans2:'.jpg',ans3:'.tif',ans4:'.ufo'},
{ans:2,que:'關於JPG 圖檔格式的敘述何者錯誤？',ans1:'瀏覽器可直接開啟',ans2:'是向量式的圖片格式',ans3:'支援全彩顯示',ans4:'採破壞性壓縮方式'},
{ans:2,que:'關於GIF 圖檔格式的敘述何者錯誤？',ans1:'副檔名為gif',ans2:'存成交錯式與透明式的GIF 格式，檔案大小大約相同',ans3:'僅支援256 色',ans4:'可製作動畫圖片效果'},
{ans:1,que:'何種圖形適合應用於儲存網頁上的小型圖示或按鈕？',ans1:'GIF',ans2:'TIF',ans3:'BMP',ans4:'WMF'},
{ans:1,que:'何種圖形檔格式可以將圖片的某部分設成透明色？',ans1:'GIF',ans2:'JPEG',ans3:'BMP',ans4:'TIFF'},
{ans:1,que:'副檔名為GIF 之檔案是何種資料？',ans1:'圖形',ans2:'文字',ans3:'程式',ans4:'指令'},
{ans:2,que:'關於網頁之副檔名，何者無法由「預設的IE6 瀏覽器」直接開啟？',ans1:'.htm',ans2:'.dwg',ans3:'.asp',ans4:'.php'},
{ans:3,que:'網站的第一頁稱之為何？',ans1:'黃頁',ans2:'封面',ans3:'首頁',ans4:'目錄'},
{ans:1,que:'製作動畫時，決定螢幕每秒鐘出現畫面數，屬於影像處理中的那一項功能？',ans1:'取樣',ans2:'辨識',ans3:'編碼',ans4:'複製'},
{ans:3,que:'何者不是正確的網頁檔案名稱？',ans1:'homepage.htm',ans2:'homepage.html',ans3:'home page.htm',ans4:'home_page.htm'},
{ans:4,que:'何者不是在網頁設定標題{ans:Title)的目的？',ans1:'顯示在瀏覽器標題列',ans2:'顯示在瀏覽器的書籤或我的最愛',ans3:'搜尋引擎用來分類並將網站增加到它們的資料庫',ans4:'加速網頁的開啟與執行'},
{ans:4,que:'一個24×24 點的中文字型，共佔用電腦記憶體多少位元組{ans:Bytes)？',ans1:'24',ans2:'48',ans3:'64',ans4:'72'},
{ans:4,que:'何者可用來檢視目前電腦上的資源被網路上其他使用者使用的狀況？',ans1:'網路安裝精靈',ans2:'遠端桌面連線',ans3:'超級終端機',ans4:'網路監控程式'},
{ans:1,que:'在Internet 的服務項目中，何者可以在網路上提供檔案搜尋的服務？',ans1:'Archie',ans2:'FTP',ans3:'Chat',ans4:'遠端登錄'},
{ans:3,que:'在Internet 的服務項目中，何者可以在網路上提供與其他使用者即時互動的功能？',ans1:'Archie',ans2:'FTP',ans3:'Chat',ans4:'遠端登錄'},
{ans:3,que:'何者不是資料庫的優點？',ans1:'減少資料重覆儲存',ans2:'節省儲存空間',ans3:'資料傳輸速度加快',ans4:'資源共享'},
{ans:2,que:'當使用「搜尋引擎」執行資料搜尋時，若欲使用兩個以上的關鍵字做複合查詢，且希望被查詢到的文件或網站同時包含有這些關鍵字，則應使用何種邏輯運算查詢？',ans1:'或{ans:OR)',ans2:'和{ans:AND)',ans3:'互斥{ans:XOR)',ans4:'反{ans:NOT)'},
{ans:3,que:'Internet Explorer 瀏覽器可藉由何種設定防止青少年進入色情及暴力等網站？',ans1:'組織我的最愛',ans2:'刪除網路頻道',ans3:'分級',ans4:'刪除記錄'},
{ans:3,que:'POP3 是設定網路連線時的何種伺服器？',ans1:'檔案伺服器',ans2:'網站伺服器',ans3:'收信伺服器',ans4:'寄信伺服器'},
{ans:4,que:'SMTP 是設定網路連線時的何種伺服器？',ans1:'檔案伺服器',ans2:'網站伺服器',ans3:'收信伺服器',ans4:'寄信伺服器'},
{ans:1,que:'Telnet 是Internet 上的一項服務，其功能為何？',ans1:'遠端登入',ans2:'電子郵件服務',ans3:'檔案傳輸服務',ans4:'電傳視訊'},
{ans:4,que:'何者不是Outlook Express 的功能？',ans1:'回信',ans2:'轉信',ans3:'附加檔案',ans4:'排定約會'},
{ans:4,que:'Outlook Express 每寄出一封信後，會保留一份在何處？',ans1:'收件匣',ans2:'寄件匣',ans3:'草稿',ans4:'寄件備份'},
{ans:2,que:'何者是「檔案傳送」所使用的通訊協定？',ans1:'HTTP',ans2:'FTP',ans3:'ISP',ans4:'MAILTO'},
{ans:3,que:'何者是「全球資訊網{ans:WWW)」所使用的通訊協定？',ans1:'FTP',ans2:'SMTP',ans3:'HTTP',ans4:'POP3'},
{ans:4,que:'何者不是「網路」所使用的通訊協定？',ans1:'NetBEUI',ans2:'TCP/IP',ans3:'IPX/SPX',ans4:'ASP'},
{ans:2,que:'何者是電子郵件「內收郵件」所使用的通訊協定？',ans1:'FTP',ans2:'POP3',ans3:'SMTP',ans4:'IPX'},
{ans:3,que:'何者是電子郵件「外寄郵件」所使用的通訊協定？',ans1:'FTP',ans2:'POP3',ans3:'SMTP',ans4:'IMAP'},
{ans:2,que:'Internet 上常用的DNS 應用系統的預設通訊埠號為何？',ans1:'110',ans2:'53',ans3:'21',ans4:'25'},
{ans:4,que:'瀏覽器應用軟體{ans:如IE 等)瀏覽網頁時通常使用的通訊埠號為何？',ans1:'21',ans2:'23',ans3:'25',ans4:'80'},
{ans:2,que:'Internet 的FTP 協定，其預設的通訊埠為何？',ans1:'80',ans2:'21',ans3:'25',ans4:'110'},
{ans:1,que:'Internet 的HTTP 協定，其預設的通訊埠為何？',ans1:'80',ans2:'21',ans3:'25',ans4:'110'},
{ans:3,que:'Internet 的SMTP 協定，其預設的通訊埠為何？',ans1:'80',ans2:'21',ans3:'25',ans4:'110'},
{ans:3,que:'在電腦網路中，使用者與遠端伺服主機連線進行檔案傳輸，所使用的協定稱之為何者？',ans1:'DNS',ans2:'BBS',ans3:'FTP',ans4:'TCP/IP'},
{ans:2,que:'在網站中設計動畫效果，其作用不包括何者？',ans1:'吸引目光',ans2:'提升傳輸速度',ans3:'模擬真實',ans4:'豐富視覺形式'},
{ans:3,que:'何者不是ISP{ans:Internet Service Provider)所提供的服務？',ans1:'提供連線上網',ans2:'提供免費個人網頁',ans3:'提供國安局機密資料全文免費查詢',ans4:'提供免費電子郵件帳號'},
{ans:2,que:'關於Internet 的敘述何者錯誤？',ans1:'TANet 是台灣學術網路',ans2:'FTP 是一種電腦網路的連接架構',ans3:'TCP/IP 是Internet常用的通訊協定',ans4:'E-mail 可以傳遞文字、影像及聲音'},
{ans:2,que:'何種伺服器具有備份使用者拜訪過網站的功能？',ans1:'FTP Server{ans:檔案傳輸伺服器)',ans2:'Proxy Server{ans:代理伺服器)',ans3:'DNS Server{ans:網域名稱伺服器)',ans4:'News Server{ans:新聞伺服器)'},
{ans:4,que:'何者不可以當作文字轉換為表格的分隔字元？',ans1:'TAB',ans2:'逗點',ans3:'Enter',ans4:'Del'},
{ans:4,que:'何者不是Internet 所提供的服務？',ans1:'News',ans2:'WWW',ans3:'BBS',ans4:'PWS'},
{ans:4,que:'何者不是WWW 的瀏覽器？',ans1:'Opera',ans2:'Mosaic',ans3:'Mozilla Firefox',ans4:'Sniffer'},
{ans:1,que:'何者不是常見的網頁搜尋入口網站？',ans1:'http://archie.edu.tw/',ans2:'http://www.google.com',ans3:'http://www.openfind.com.tw',ans4:'http://gais.cs.ccu.edu.tw/'},
{ans:4,que:'何者不是圖片超連結可以設定的功能？',ans1:'低解析度顯示',ans2:'替代顯示文字',ans3:'指定圖片類型與品質',ans4:'圖片排序'},
{ans:4,que:'何者無法用來架設WWW 伺服器？',ans1:'雷電HTTPD',ans2:'IIS',ans3:'Apache',ans4:'Serv-U'},
{ans:2,que:'何者不屬於自由軟體？',ans1:'PHP-Nuke',ans2:'Norton Internet Security',ans3:'XOOPS',ans4:'OpenOffice.org'},
{ans:3,que:'何者是匿名登入FTP 站所使用的帳號？',ans1:'everyone',ans2:'anyone',ans3:'anonymous',ans4:'root'},
{ans:2,que:'何者是常用的Web 伺服器？',ans1:'Exchange',ans2:'IIS',ans3:'SQL',ans4:'Lotus Notes'},
{ans:4,que:'何者為ASP 的語法符號？',ans1:'@',ans2:'&',ans3:'#',ans4:'%'},
{ans:4,que:'何者為TANet 之中文意義？',ans1:'全球資訊網',ans2:'網際網路',ans3:'電子郵件',ans4:'台灣學術網路'},
{ans:2,que:'何者為匿名登入FTP 站時，伺服器會要求使用的密碼？',ans1:'你的生日',ans2:'你的電子郵件',ans3:'你的名字',ans4:'你的電話號碼'},
{ans:1,que:'提供檔案下載功能的是那類伺服器？',ans1:'FTP server',ans2:'Proxy server',ans3:'DHCP server',ans4:'Web server'},
{ans:2,que:'那個FTP 指令可以用來查看遠端FTP 伺服器目前所在目錄之位置？',ans1:'get',ans2:'pwd',ans3:'put',ans4:'bin'},
{ans:3,que:'那個FTP 指令可以將本地端機器的檔案傳輸至遠端FTP 伺服器上？',ans1:'get',ans2:'pwd',ans3:'put',ans4:'bin'},
{ans:3,que:'FTP 是Internet 上的一項服務，其功能為何？',ans1:'遠端登入',ans2:'電子郵件服務',ans3:'檔案傳輸服務',ans4:'電傳視訊'},
{ans:2,que:'何者為PHP 的語法符號？',ans1:'@',ans2:'?',ans3:'#',ans4:'$'},
{ans:2,que:'內容管理系統{ans:Content Management System,CMS)常用來製作入口網站，何者不屬於CMS？',ans1:'XOOPS',ans2:'Sleipnir',ans3:'Manbo',ans4:'PHP-Nuke'},
{ans:2,que:'何種語言可以編撰網頁的動態效果？',ans1:'BASIC',ans2:'Java Applets',ans3:'FORTRAN',ans4:'COBOL'},
{ans:3,que:'電子郵件傳送附加檔案需要1 分鐘，同樣的郵件同時傳送給100 人，理論上需要多少時間？',ans1:'1 分鐘',ans2:'10 分鐘',ans3:'100 分鐘',ans4:'1000 分鐘'},
{ans:4,que:'何者為電子郵件軟體？',ans1:'PhotoImpact',ans2:'Flash',ans3:'Visio',ans4:'Outlook'},
{ans:3,que:'關於E-mail 之敘述何者錯誤？',ans1:'寄發電子郵件必須要有收件人的E-mail Address',ans2:'E-mail 可以透過電話線來傳送',ans3:'E-mail 傳送時，沒有指定主旨的信件一定無法傳送',ans4:'發信人可以同時將信件傳送給二位以上的收信人'},
{ans:1,que:'何種功能可使電子郵件的附件在寄送時，節省傳送的時間？',ans1:'壓縮',ans2:'回傳給本人',ans3:'加密',ans4:'密件副本'},
{ans:1,que:'使用Outlook Express 要寄信給許多人，每個E-Mail 間需要用那一個符號隔開？',ans1:';',ans2:'-',ans3:'.',ans4:'@'},
{ans:4,que:'何種功能可使電子郵件在寄送時，不想讓收件者知道何者收到此信件？',ans1:'壓縮',ans2:'回傳給本人',ans3:'加密',ans4:'密件副本'},
{ans:2,que:'網路日誌又稱為「部落格{ans:blog)」，何者無法用來架設個人網路日誌？',ans1:'Movable Type',ans2:'WordPad',ans3:'WordPress',ans4:'pLog'},
{ans:4,que:'關於圖形檔案格式的敘述何者錯誤？',ans1:'GIF89a 只能支援256 色',ans2:'PNG 格式支援全彩',ans3:'TIF 格式必須轉換才能置於網頁上',ans4:'GIF 檔案採用失真壓縮技術'},
{ans:4,que:'以PhotoImpact 10 處理需要「去除背景」的圖片時，若要快速選取背景顏色很接近的區域，最好使用何種工具按鈕？',ans1:'標準選取',ans2:'貝茲曲線',ans3:'索套',ans4:'魔術棒'},
{ans:2,que:'要將Internet Explorer 6 網頁畫面中的圖片設成桌面底色圖案，應執行那個動作？',ans1:'在圖片上按滑鼠右鍵選取「到我的圖片」',ans2:'在圖片上按滑鼠右鍵選取「設成背景」',ans3:'在圖片上按滑鼠右鍵選取「加到我的最愛」',ans4:'以滑鼠選取圖片，再點選[編輯]功能表中的「複製」命令'},
{ans:1,que:'要設定Internet Explorer 6 透過Proxy 伺服器連接Internet，應執行那個動作？',ans1:'執行[工具]\[網際網路選項]，在[連線]標籤中設定',ans2:'執行[工具]\[網際網路選項]，在[一般]標籤中設定',ans3:'執行[工具]\[同步處理]',ans4:'開啟[控制台]\[撥號網路]'},
{ans:3,que:'何種方法可以將使用Internet Explorer 6 拜訪過的網站分類保存起來，讓下次可以快速地進入該網站？',ans1:'加到「搜尋」',ans2:'加到「記錄」',ans3:'加到「我的最愛」',ans4:'加入到通訊錄中'},
{ans:4,que:'在Internet 上，何種伺服器可將網路主機名稱{ans:如：www.labor.gov.tw)翻譯成IP 位址？',ans1:'Mail Server',ans2:'File Server',ans3:'Proxy Server',ans4:'Domain Name Server'},
{ans:3,que:'Word 2003 軟體要將目前正在編輯的文件內容儲存成網頁，可執行「檔案」功能表內的那個選項來完成？',ans1:'開新檔案',ans2:'儲存檔案',ans3:'另存成網頁',ans4:'結束'},
{ans:4,que:'有關於Excel 2003 的敘述何者為非？',ans1:'工作表可以儲存成互動式網頁',ans2:'透過瀏覽器可以瀏覽工作表',ans3:'透過瀏覽器可以編輯工作表的內容',ans4:'不支援另存成*.mht 單一檔案網頁功能'},
{ans:4,que:'那一個應用軟體所產生的檔案無法直接存成網頁格式？',ans1:'Word',ans2:'Excel',ans3:'PowerPoint',ans4:'Access'},
{ans:2,que:'瀏覽器無法直接讀取的檔案格式，必須藉由何者才能順利讀取？',ans1:'Abs',ans2:'Plug-In',ans3:'Animator',ans4:'PhotoImpact'},
{ans:4,que:'輸入那個文字是無法建立超連結的？',ans1:'mailto:',ans2:'http://',ans3:'ftp://',ans4:'tcp/ip'},
{ans:1,que:'網頁中之Applet 及Servlet 是用何種語言來撰寫的？',ans1:'Java',ans2:'C++',ans3:'Java Script',ans4:'BASIC'},
{ans:3,que:'影像處理時，將圖片由全彩轉成256 色灰階，則該圖片的每一個像素使用多少位元來描述表示？',ans1:'2 位元',ans2:'4位元',ans3:'8 位元',ans4:'24 位元'},
{ans:2,que:'替ActiveX 控制項命名時，何者不可以使用？',ans1:'英文字母',ans2:'空格',ans3:'阿拉伯數字',ans4:'大寫文字'},
{ans:4,que:'網頁中的表單處理程式，在使用者按下傳送鈕後，無法將結果傳送到何處？',ans1:'指定的檔案',ans2:'指定資料庫',ans3:'指定電子郵件地址',ans4:'訪客的CD-ROM'},
{ans:4,que:'網頁表單處理程式無法使用何種語言來撰寫？',ans1:'ASP.NET',ans2:'PHP',ans3:'JSP',ans4:'FORTRAN'},
{ans:3,que:'關於超連結的敘述何者錯誤？',ans1:'圖片可以設定超連結',ans2:'可以使用書籤連結網頁內其它位置',ans3:'超連結只能使用絕對路徑連結',ans4:'E-mail 位址也可以設定連結'},
{ans:2,que:'網頁設計之影像地圖具有何種功能？',ans1:'文字超連結',ans2:'圖片超連結',ans3:'資料夾超連結',ans4:'不屬於超連結功能'},
{ans:4,que:'何者不屬於可以添加在網頁上的動畫元件？',ans1:'跑馬燈',ans2:'廣告橫幅',ans3:'計數器',ans4:'CAD 圖檔'},
{ans:1,que:'何者是傳遞填寫表單資料的控制項？',ans1:'提交{ans:submit)',ans2:'重新設定{ans:reset)',ans3:'核取方塊{ans:checkbox)',ans4:'文字方塊{ans:textbox)'},
{ans:2,que:'設定同一網頁內的超連結，必須事先設定何者？',ans1:'頁首',ans2:'書籤',ans3:'頁尾',ans4:'圖形'},
{ans:1,que:'設定的超連結文字在預設狀態下為何？',ans1:'加上底線的文字',ans2:'變成斜體字的文字',ans3:'變成浮動的文字',ans4:'加上動態閃爍效果的字'},
{ans:3,que:'建立一個分成上、中、下三個框架的網頁，儲存時應該要儲存成幾個網頁檔案？',ans1:'一個',ans2:'三個',ans3:'四個',ans4:'五個'},
{ans:4,que:'運用何種方式可以節省網頁設計所佔的空間？',ans1:'將網頁分類',ans2:'使用動態GIF 檔案',ans3:'將圖片排序',ans4:'降低圖片的大小及解析度'},
{ans:1,que:'何者具備網頁製作及網站管理的功能？',ans1:'Namo WebEditor',ans2:'WordPad',ans3:'Word',ans4:'Flash'},
{ans:3,que:'Dreamweaver CS3 設計網頁，當滑鼠移入某個連結點時會出現預先設計好的圖層文字，在行為指令中應選取何者？',ans1:'onClick',ans2:'onDblClick',ans3:'onMouseOver',ans4:'onMouseOut'},
{ans:3,que:'關於Dreamweaver CS3 的敘述何者錯誤？',ans1:'可使用CSS 樣式',ans2:'可建立表單',ans3:'內建網頁切換轉場效果',ans4:'可製作影像地圖'},
{ans:3,que:'Dreamweaver CS3 無外掛程式的情況下，網頁上的圖片無法設定何項工作？',ans1:'絕對位置的設定',ans2:'上推一層',ans3:'圖片式跑馬燈',ans4:'超連結'},
{ans:3,que:'Dreamweaver CS3 建立表單之文字欄位時，「字元寬度」輸入的數值若為10，則其表示為何？',ans1:'最少10 個英文字母',ans2:'最少10 個中文字',ans3:'最多10 個英文字母',ans4:'最多10 個中文字'},
{ans:1,que:'Dreamweaver CS3 建立內部CSS 樣式表時，應將CSS 語法寫在那個標籤內？',ans1:'＜style＞與＜/style＞',ans2:'＜IMG＞',ans3:'＜link＞',ans4:'＜P＞與＜/P＞'},
{ans:2,que:'Dreamweaver CS3 建立網頁時，新增一個行為，其實是套用何種語法？',ans1:'ASP',ans2:'Java Script',ans3:'PHP',ans4:'VBScript'},
{ans:1,que:'Dreamweaver CS3 製作表單時，何種控制項適合單一選項的應用？',ans1:'選擇圓鈕',ans2:'下拉式清單選項',ans3:'文字方塊',ans4:'核取方塊'},
{ans:2,que:'安裝何種軟體可以編輯網頁及管理網站？',ans1:'Excel 2003',ans2:'FrontPage 2003',ans3:'Word 2003',ans4:'Access 2003'},
{ans:2,que:'使用Microsoft FrontPage 編輯網頁時，要強迫換列的按鍵方式為何？',ans1:'Ctrl+Enter',ans2:'Shift+Enter',ans3:'Alt+Enter',ans4:'Enter'},
{ans:4,que:'何種元件不需要FrontPage 2000 Server Extensions 支援，就具備該元件的功能？',ans1:'計數器元件',ans2:'排程共用網頁元件',ans3:'表單確認欄位',ans4:'跑馬燈'},
{ans:1,que:'FrontPage 2003 製作網頁，要儲存網頁上的框架頁時，可以選取該框架後，執行什麼命令？',ans1:'儲存檔案',ans2:'開新網頁',ans3:'關閉檔案',ans4:'列印檔案'},
{ans:4,que:'何種方式不適合用來發佈所建立的FrontPage 2003 網站？',ans1:'使用IE 的Web 發佈精靈來發送網站',ans2:'透過FrontPage 2003 的發送Web 功能',ans3:'藉由FTP 來傳送網站資料',ans4:'直接壓縮再複製檔案'},
{ans:4,que:'FrontPage 2003 的環境裡，提供使用者將一組圖片依照指定的版面設計快速產生縮圖及圖片超連結網頁的設計為何？',ans1:'導覽列的設計',ans2:'佈景主題的設計',ans3:'互動式按鈕',ans4:'相片藝廊'},
{ans:1,que:'FrontPage 2003 若要以手動方式建立框架，該如何操作？',ans1:'分割框架',ans2:'合併框架',ans3:'複製框架',ans4:'刪除框架'},
{ans:3,que:'FrontPage 2003 框架內容，何者無法設定框架？',ans1:'邊界高度',ans2:'框架大小',ans3:'框架邊框色',ans4:'捲動軸的顯示與否'},
{ans:1,que:'FrontPage 2003 設定網頁背景音樂時，可以操作那一個指令？',ans1:'格式/背景',ans2:'檔案/版面設定',ans3:'格式/佈景主題',ans4:'檔案/插入'},
{ans:3,que:'FrontPage 2003 製作網頁上的表格框線其大小若設為零，結果為何？',ans1:'會合併表格裡面的儲存格',ans2:'產生很細小的框線',ans3:'沒有框線',ans4:'產生錯誤訊息並無法操作'},
{ans:1,que:'FrontPage 2003 提供何種功能，可以讓按鈕在滑鼠指標尚未移上去之前展現一種風貌，而滑鼠指標移上去之後又變成另外一種風貌？',ans1:'互動式按鈕',ans2:'浮動按鈕',ans3:'連結列',ans4:'相片藝廊'},
{ans:2,que:'FrontPage 2003 可以使用何者建立資料庫的銜接？',ans1:'計數器',ans2:'ODBC',ans3:'排程網頁',ans4:'網頁橫幅'},
{ans:1,que:'FrontPage 2003 框架的設定中，「開新視窗」的目標設定為何？',ans1:'_blank',ans2:'_top',ans3:'_parent',ans4:'_home'},
{ans:3,que:'欲在同一張圖片上製作多個超連結到多個目的網頁之作法為何？',ans1:'建立文字超連結',ans2:'建立書籤超連結',ans3:'建立影像地圖超連結',ans4:'建立電子郵件超連結'},
{ans:4,que:'何者不是FrontPage 2003 軟體之影像地圖預設的標示？',ans1:'矩形',ans2:'圓形',ans3:'多角形',ans4:'菱形'},
{ans:3,que:'FrontPage 2003 製作網頁之敘述何者錯誤？',ans1:'若將圖片縮小，並不會使得圖檔佔用空間變小',ans2:'若進行圖片的裁減，也會使得圖檔佔用空間變小',ans3:'GIF 檔案不支援透明色',ans4:'您可以使文字方塊在插入的圖片上編輯文字'},
{ans:4,que:'FrontPage 2003 製作網頁時，插入至網頁上的圖片並無何項功能？',ans1:'左右翻轉',ans2:'上下翻轉',ans3:'設定透明色系',ans4:'除刮痕'},
{ans:1,que:'FrontPage 2003 的環境裡，在排定時間內顯示某個指定網頁的功能稱之為何？',ans1:'排程網頁',ans2:'流程網頁',ans3:'指定網頁',ans4:'程式網頁'},
{ans:4,que:'Web 伺服器安裝了什麼軟體，就可以設定資料儲存至網頁、文字檔案及資料庫內？',ans1:'Word',ans2:'Excel',ans3:'PowerPoint',ans4:'Frontpage Server Extensions'},
{ans:3,que:'那一種語言是專門用來撰寫全球資訊網（World Wide Web）中的網頁？',ans1:'Assembly Language',ans2:'Data Control Language',ans3:'Hypertext Markup Language',ans4:'Structured Query Language'},
{ans:3,que:'何者不是常用的網頁格式？',ans1:'HTML',ans2:'DHTML',ans3:'PASCAL',ans4:'XML'},
{ans:2,que:'HTML{ans:HyperText Markup Language)標準是由那一個單位制定的？',ans1:'IEEE',ans2:'W3C',ans3:'ISO',ans4:'EIA'},
{ans:1,que:'W3C 認為HTML4.01 之後已經沒有發展新版本的必要，將由那ㄧ個功能性更佳的語言來取代？',ans1:'XHTML',ans2:'XML',ans3:'SGML',ans4:'DHTML'},
{ans:1,que:'首頁的檔案名稱通常預設為何？',ans1:'index.htm',ans2:'first.htm',ans3:'start.htm',ans4:'head.htm'},
{ans:3,que:'何者語言無法展現在網頁文件上？',ans1:'JavaApplet',ans2:'HTML 語言',ans3:'BASIC 語言',ans4:'VB Script'},
{ans:2,que:'表格的製作上，HTML 原始碼所使用的標籤為何？',ans1:'TAB',ans2:'Table',ans3:'Tag',ans4:'表格'},
{ans:3,que:'HTML 的標籤是以何種符號標示？',ans1:'｛與｝',ans2:'（與）',ans3:'＜與＞',ans4:'〔與〕'},
{ans:4,que:'HTML 的語法中，那個標籤名稱{ans:tag)用來表示文件的主體？',ans1:'HTML',ans2:'TITLE',ans3:'HEAD',ans4:'BODY'},
{ans:1,que:'HTML 的語法中，那個標籤名稱{ans:tag)用來設定對齊方式的？',ans1:'ALIGN',ans2:'STYLE',ans3:'WIDTH',ans4:'DIV'},
{ans:1,que:'HTML 的語法中，那個標籤名稱{ans:tag)是用來加入超連結？',ans1:'HREF',ans2:'FONT',ans3:'IMG',ans4:'ALIGN'},
{ans:3,que:'HTML 的語法中，＜a＞標籤裡那個屬性是用來定義連結書籤？',ans1:'HREF',ans2:'OBJECT',ans3:'NAME',ans4:'BASE'},
{ans:4,que:'HTML 的語法中，何者為＜FRAMESET＞標籤的功能？',ans1:'設定邊框大小',ans2:'開啟新視窗',ans3:'設定基底路徑',ans4:'分割視窗'},
{ans:4,que:'HTML 的語法中，那個標籤可以設定背景聲音？',ans1:'＜FRAME＞',ans2:'＜FORM＞',ans3:'＜TABLE＞',ans4:'＜BGSOUND＞'},
{ans:3,que:'HTML 的語法中，那個標籤無法設定播放聲音？',ans1:'＜EMBED SRC="hi.wav"＞',ans2:'＜BODY ONLOAD="location.href=hi.wav"＞',ans3:'＜IMG SRC="hi.wav"＞',ans4:'＜BGSOUND SRC="hi.wav"＞'},
{ans:4,que:'HTML 的語法中，那一個標籤{ans:tag)與文字設定無關？',ans1:'＜B＞…＜/B＞',ans2:'＜I＞…＜/I＞',ans3:'＜U＞…＜/U＞',ans4:'＜HR＞…＜/HR＞'},
{ans:1,que:'HTML 的語法＜HTML＞…＜/HTML＞其作用為何？',ans1:'宣告HTML 文件的開始與結束',ans2:'宣告HTML 文件的開頭部分',ans3:'宣告HTML 的主體部分',ans4:'宣告HTML 文件的結尾部分'},
{ans:3,que:'HTML 的語法＜BODY＞…＜/BODY＞其作用為何？',ans1:'宣告HTML 文件的開始與結束',ans2:'宣告HTML 文件的開頭部分',ans3:'宣告HTML 的主體部分',ans4:'宣告HTML 文件的結尾部分'},
{ans:2,que:'HTML 的語法＜HEAD＞…＜/HEAD＞其作用為何？',ans1:'宣告HTML 文件的開始與結束',ans2:'宣告HTML 文件的開頭部分',ans3:'宣告HTML 的主體部分',ans4:'宣告HTML 文件的結尾部分'},
{ans:4,que:'HTML 的語法＜TABLE＞…＜/TABLE＞其作用為何？',ans1:'插入水平分隔線',ans2:'插入圖片',ans3:'插入背景',ans4:'插入表格'},
{ans:1,que:'HTML 的語法＜HR＞其作用為何？',ans1:'插入水平分隔線',ans2:'插入圖片',ans3:'插入背景',ans4:'插入表格'},
{ans:2,que:'HTML 的語法＜IMG SRC=”samatha.jpg” BORDER=”5” WIDTH=”400” HEIGTH=”300”＞其作用為何？',ans1:'插入水平分隔線',ans2:'插入圖片',ans3:'插入背景',ans4:'插入表格'},
{ans:3,que:'HTML 的語法＜FONT SIZE="5" COLOR="#FF0000"＞…＜/FONT＞其作用為何？',ans1:'設定水平分隔線',ans2:'設定圖片',ans3:'設定文字',ans4:'設定表格'},
{ans:4,que:'HTML 的語法＜FONT SIZE="3" COLOR="#0000FF"＞…＜/FONT＞其設定的物件顏色為何？',ans1:'紅色',ans2:'黃色',ans3:'綠色',ans4:'藍色'},
{ans:2,que:'HTML 的語法＜FRAMESET＞…＜/FRAMESET＞其作用為何？',ans1:'設定分隔線',ans2:'設定框架',ans3:'設定文字',ans4:'設定表格'},
{ans:2,que:'HTML 的語法中，超連結的網頁欲在新視窗開啟，TAGET 應設為何？',ans1:'_self',ans2:'_blank',ans3:'_top',ans4:'_parent'},
{ans:1,que:'HTML 的語法＜TITLE＞…＜/TITLE＞其作用為何？',ans1:'設定標題',ans2:'設定框架',ans3:'設定文字',ans4:'設定表格'},
{ans:4,que:'HTML 的語法＜BODY LINK="#0000FF" VLINK="#FF0000" ALINK="#FFFF00"＞其功能表示尚未點選超連結過的物件顏色為何？',ans1:'紅色',ans2:'黃色',ans3:'綠色',ans4:'藍色'},
{ans:1,que:'HTML 的語法＜BODY LINK="#0000FF" VLINK="#FF0000" ALINK="#FFFF00"＞其功能表示已點選超連結過的物件顏色為何？',ans1:'紅色',ans2:'黃色',ans3:'綠色',ans4:'藍色'},
{ans:2,que:'HTML 的語法中，要連結至書籤時，何者正確？',ans1:'＜A NAME="myphoto"＞',ans2:'＜A HREF="#myphoto"＞',ans3:'＜A HREF="http://www.kimo.com.tw"＞',ans4:'＜A LINK="myphoto"＞'},
{ans:1,que:'HTML 的語法中，何者可以在文字上加入粗體及斜體的效果？',ans1:'＜B＞＜I＞',ans2:'＜B＞＜P＞',ans3:'＜EM＞＜Strong＞',ans4:'＜EM＞＜TT＞'},
{ans:4,que:'HTML 的語法中，何者可以將文字的段落和字元按照原本的編排樣式顯示出來{ans:即換行字元及空白字元完全被保留)？',ans1:'＜BODY＞',ans2:'＜P＞',ans3:'＜EM＞',ans4:'＜PRE＞'},
{ans:2,que:'在利用「HTML 語言」撰寫網頁時，若撰寫此行＜TITLE＞職訓局的網站＜/TITLE＞的語法，則「職訓局的網站」將會被顯示在何處？',ans1:'瀏覽視窗',ans2:'瀏覽器的標題列',ans3:'在這份文件內容的最上面',ans4:'狀態列'},
{ans:2,que:'何者是HTML 所使用的註解格式？',ans1:'//網頁註解',ans2:'＜!--網頁註解--＞',ans3:'’網頁註解',ans4:'/*網頁註解*/'},
{ans:1,que:'何者為HTML 語法的起始與結束標籤？',ans1:'＜HTML＞與＜/HTML＞',ans2:'＜BODY＞與＜/BODY＞',ans3:'＜TITLE＞與＜/TITLE＞',ans4:'＜P＞與＜/P＞'},
{ans:1,que:'HTML 的語法中，那個標籤可以在網頁上顯示labor.jpg 的圖形檔？',ans1:'＜IMG SRC="labor.jpg"＞',ans2:'＜INPUT SRC="labor.jpg"＞',ans3:'＜OBJECT="labor.jpg"＞',ans4:'＜NAME="labor.jpg"＞'},
{ans:1,que:'若在網頁中加入HTML 語言：＜A HREF="taiwan.jpg"＞＜IMG SRC="taiwan.gif" ALT="按我可以放大"＞＜/A＞，則訪客在圖形上按下滑鼠時，執行結果為何？',ans1:'超連結到taiwan.jpg 圖形上',ans2:'出現文字"按我可以放大"',ans3:'將taiwan.gif 圖片存檔',ans4:'將taiwan.jpg 圖片存檔'},
{ans:4,que:'JavaScript 程式執行結果為何？',ans1:'2',ans2:'4',ans3:'18',ans4:'36',img:'2200.png'},
{ans:4,que:'JavaScript 程式執行結果為何？',ans1:'LI=2',ans2:'LI=3',ans3:'．x%y=2',ans4:'．x%y=3',img:'2201.png'},
{ans:4,que:'何者不是「視訊檔」的副檔名？',ans1:'.wmv',ans2:'.mpg',ans3:'.asf',ans4:'.bmp'},
{ans:4,que:'何種軟體無法透過電腦與朋友線上語音交談？',ans1:'NetMeeting',ans2:'Skype',ans3:'MSN Messenger',ans4:'Media Player 9'},
{ans:4,que:'電子郵件信箱 E-mail 帳號中必須有那一個符號？',ans1:'!',ans2:'&',ans3:'*',ans4:'@'},
{ans:4,que:'電腦上RGB 的色盤設為{ans:255,255,0)時，其顯示的顏色為何？',ans1:'淡藍色',ans2:'綠色',ans3:'紫色',ans4:'黃色'},
{ans:2,que:'電腦上RGB 的色盤設為{ans:255,255,255)時，其顯示的顏色為何？',ans1:'黑色',ans2:'白色',ans3:'灰色',ans4:'金色'},
{ans:4,que:'何者不是安裝Web Server 的軟體？',ans1:'Apache Server',ans2:'PWS',ans3:'IIS',ans4:'DHCP'},
{ans:4,que:'對於JAVA 語言而言，運用在瀏覽器環境上的程式稱為？',ans1:'MIDlet',ans2:'Spotlet',ans3:'JSP',ans4:'Applet'},
{ans:4,que:'用來服務用戶端網頁瀏覽的伺服器為何？',ans1:'FTP server',ans2:'Proxy server',ans3:'DHCP server',ans4:'Web server'},
{ans:1,que:'何者不是伺服端{ans:Server Side)的腳本語言{ans:Script)？',ans1:'JavaScript',ans2:'ASP',ans3:'JSP',ans4:'PHP'},
{ans:2,que:'在正常操作環境下，何種軟體程式無法直接將Internet 網站上的圖片複製下來使用？',ans1:'Word',ans2:'Notepad',ans3:'FrontPage',ans4:'Dreamweaver'},
{ans:1,que:'何者不是所見所得{ans:What you see is what you get)的網頁編輯軟體？',ans1:'Notepad',ans2:'ForntPage',ans3:'Dreamweaver',ans4:'Namo'},
{ans:1,que:'何種圖形檔案格式最不適合使用網頁上？',ans1:'TIF',ans2:'GIF',ans3:'JPEG',ans4:'PNG'},
{ans:3,que:'何種視訊檔案格式最不適合使用網頁上？',ans1:'QuickTime',ans2:'MPEG',ans3:'AVI',ans4:'WMV'},
{ans:3,que:'何者為電子郵件應用軟體通常使用的連接埠？',ans1:'21',ans2:'23',ans3:'25',ans4:'80'},
{ans:3,que:'電子郵件的位址格式何者正確？',ans1:'http://www.google.com',ans2:'ftp://210.85.82.20',ans3:'amis@labor.gov.tw',ans4:'gopher://gopher.ntnu.edu.tw'},
{ans:4,que:'何者不是Internet 上使用的瀏覽器？',ans1:'Internet Explorer',ans2:'Mozilla Firefox',ans3:'Opera',ans4:'Fedora'},
{ans:4,que:'Internet Explorer 不能支援的背景聲音為何？',ans1:'MIDI',ans2:'WAV',ans3:'MP3',ans4:'CDR'},
{ans:2,que:'Microsoft 發行之軟體IE 7 是屬於那一用途之軟體？',ans1:'文書編輯器',ans2:'網路瀏覽器',ans3:'統計分析',ans4:'電腦輔助設計'},
{ans:2,que:'定義網頁資料顯示、格式化、特殊效果的標準稱之為何？',ans1:'CIS',ans2:'CSS',ans3:'ABS',ans4:'CCS'},
{ans:2,que:'何種軟體無法播放MPGE 影片？',ans1:'Media Player',ans2:'AnyDVD',ans3:'PowerDVD',ans4:'RealPlayer'},
{ans:2,que:'何者不是用在網頁中以增強網頁效果或功能？',ans1:'PHP',ans2:'ICQ',ans3:'XML',ans4:'ASP'},
{ans:1,que:'在設計網頁時，欲使用聲音效果，何種聲音檔案格式最不利網路傳輸速度的考量？',ans1:'WAV',ans2:'MIDI',ans3:'MP3',ans4:'WMA'},
{ans:1,que:'Windows Media Player 無法播放何種影音檔案？',ans1:'Flash 動畫',ans2:'音樂CD',ans3:'VCD',ans4:'MP3'}]