// JavaScript Document
que3=[{ans:1,que:'作業系統的主要功能為記憶體管理、處理機管理、設備管理，以及那一項？',ans1:'I/O 管理',ans2:'資料管理',ans3:'程式管理',ans4:'中文管理'},
{ans:4,que:'何種作業系統沒有圖形使用者操作介面？',ans1:'Linux',ans2:'Windows NT',ans3:'Windows 7',ans4:'MS-DOS'},
{ans:4,que:'何者為掌上型電腦的作業系統？',ans1:'Windows 7',ans2:'Linux',ans3:'Mac OS',ans4:'Pocket PC'},
{ans:3,que:'何者不是多工{ans:Multi-tasking)作業系統？',ans1:'Linux',ans2:'OS/2',ans3:'DOS',ans4:'Windows 7'},
{ans:3,que:'何種作業系統之檔案名稱對英文字母大小寫不區分？',ans1:'Free BSD',ans2:'Unix',ans3:'Windows',ans4:'Linux'},
{ans:1,que:'何種作業系統最不可能具有遠端登入的功能？',ans1:'MS-DOS',ans2:'Windows XP',ans3:'Windows Server 2003',ans4:'Linux'},
{ans:4,que:'何者不是多人多工的作業系統？',ans1:'Free BSD',ans2:'Linux',ans3:'Solaris',ans4:'Windows XP'},
{ans:4,que:'程式多工處理{ans:Multi-processing)的工作原理為何？',ans1:'處理完一件工作後，才處理下一件工作',ans2:'電腦同時段內可處理多件工作',ans3:'同時段內處理所有工作的輸出入動作{ans:I/O operation)',ans4:'電腦可處理多個工作{ans:process)，但同一時段內只處理一件'},
{ans:2,que:'何者不是網路作業系統{ans:NOS)？',ans1:'Windows 2008 Server',ans2:'Windows Me',ans3:'Unix',ans4:'Linux'},
{ans:1,que:'那一種作業系統不支援長檔名？',ans1:'MS_DOS',ans2:'OS/2',ans3:'Windows XP',ans4:'Unix'},
{ans:2,que:'何種作業系統無法安裝在PC 上被使用？',ans1:'Linux',ans2:'VAX-11',ans3:'Windows XP',ans4:'Windows 2008 Server'},
{ans:4,que:'何者不是一般的作業系統可以提供的功能？',ans1:'分時{ans:Time-sharing)作業',ans2:'多工{ans:Multi-tasking)作業',ans3:'硬碟管理',ans4:'程式翻譯{ans:Language Translation)作業'},
{ans:3,que:'安裝Linux 時，若主記憶體為128MB 則建立SWAP 分割區的大小為多少較適當？',ans1:'512MB',ans2:'128MB',ans3:'256MB',ans4:'2GB'},
{ans:3,que:'何者是Linux 作業系統「系統管理者」的預設帳號？',ans1:'administrator',ans2:'manager',ans3:'root',ans4:'supervisor'},
{ans:1,que:'Windows XP 執行那一個指令可以查詢本地電腦的IP 組態？',ans1:'ipconfig',ans2:'tracert',ans3:'route',ans4:'ping'},
{ans:2,que:'Windows XP 執行那一個指令可以查詢本地電腦傳送資料到遠端電腦的路徑？',ans1:'ipconfig',ans2:'tracert',ans3:'route',ans4:'ping'},
{ans:1,que:'Windows XP 要提供資源共用，何者設定不需要？',ans1:'必須以Windows 登入為主網路登入',ans2:'必須以Client for Microsoft Networks 為主網路登入',ans3:'必須安裝Client for Microsoft Networks 用戶端',ans4:'必須安裝File and Printer sharing forMicrosoft Networks 服務'},
{ans:3,que:'何者不是Windows XP 開機時必要的檔案？',ans1:'Msdos.sys',ans2:'Command.com',ans3:'Autoexec.bat',ans4:'Io.sys'},
{ans:1,que:'何者是Windows XP 預設的通訊協定？',ans1:'TCP/IP',ans2:'IPX/SPX 相容通訊協定',ans3:'NetBEUI',ans4:'AppleTalk'},
{ans:2,que:'Windows XP「控制台」的「系統」中，若要依裝置類型來檢視電腦中的硬體裝置，則應在那個標籤下查看？',ans1:'一般',ans2:'硬體/裝置管理員',ans3:'進階/效能選項',ans4:'硬體/硬體設定檔'},
{ans:4,que:'在Windows XP「控制台」的「顯示」中，若要更改顯示器的色彩及解析度，則應在那一個標籤下設定？',ans1:'效果',ans2:'背景',ans3:'外觀',ans4:'設定值'},
{ans:4,que:'在Windows XP「開始」的「搜尋」功能表中，若選擇「Internet」的選項，何者可能為其尋找的對象？',ans1:'IP 位址',ans2:'網域名稱',ans3:'群組名稱',ans4:'網頁內容'},
{ans:1,que:'Windows XP「開始」的「搜尋」功能表中，若選擇「檔案或資料夾」的選項，那一個敘述是錯誤的？',ans1:'可以指定要尋找檔案的屬性',ans2:'可以指定要尋找檔案的大小範圍',ans3:'可以指定要尋找檔案的資料夾',ans4:'可以指定要尋找檔案的修改日期範圍'},
{ans:4,que:'Windows XP 要查詢一個中文字的內碼，則可使用何種方式達成？',ans1:'「控制台」中的「字型」',ans2:'「控制台」中的「鍵盤」',ans3:'「控制台」中的「輸入法」',ans4:'字元對應表'},
{ans:2,que:'Windows XP「控制台」的「顯示」中，若要更換顯示器的桌面圖案，則應在那一個標籤下設定？',ans1:'效果',ans2:'背景',ans3:'外觀',ans4:'設定值'},
{ans:2,que:'Windows 系統中預設滑鼠左鍵點一下不放，並移動滑鼠是要執行什麼動作？',ans1:'選取',ans2:'拖放',ans3:'執行',ans4:'點選'},
{ans:4,que:'Windows 系統中預設滑鼠左鍵點一下是要執行什麼動作？',ans1:'選單',ans2:'拖放',ans3:'執行',ans4:'點選'},
{ans:1,que:'在Windows XP 中，使用何種介面的技術，可讓電腦能夠更容易辨識出其硬體裝置？',ans1:'Plug&Play',ans2:'IDE',ans3:'SCSI',ans4:'PCMCIA'},
{ans:2,que:'Windows XP{ans:Service Pack 2)若只按一次Ctrl＋Alt＋Delete 鍵，則會進行那一個動作？',ans1:'關機',ans2:'出現Windows 安全性對話方塊',ans3:'重新開機',ans4:'不會執行任何動作'},
{ans:2,que:'Windows XP 要「更改檔案屬性」，則在選取該檔案後，再按一下滑鼠右鍵，然後在「快顯功能表」中選取那一個選項去完成？',ans1:'更名',ans2:'內容',ans3:'建立捷徑',ans4:'傳送到'},
{ans:1,que:'關於Windows XP「檔案總管」的敘述中，何者不正確？',ans1:'可以用來分割硬碟區間',ans2:'可以用來製作格式',ans3:'可以用來複製磁片',ans4:'可用來尋找檔案'},
{ans:1,que:'Windows XP 要偵測本端主機和遠端主機間的網路是否為連通狀態時，則應執行那一個指令？',ans1:'ping',ans2:'ipconfig',ans3:'telnet',ans4:'route'},
{ans:1,que:'Windows XP 要連上全球資訊網，則必須在網路中設定那一種通訊協定？',ans1:'TCP/IP',ans2:'PPP',ans3:'NetBEUI',ans4:'IPX/SPX'},
{ans:1,que:'Windows XP 要透過電話撥接連上Internet，那一動作是不需要？',ans1:'使用ISDN 線路',ans2:'安裝TCP/IP 通訊協定',ans3:'安裝數據機',ans4:'安裝撥號配接卡'},
{ans:3,que:'Windows XP 要截取「某一個工作中的視窗」成為一個圖案時，則應按那一組按鍵？',ans1:'PrintScreen',ans2:'Shift+PrintScreen',ans3:'Alt+PrintScreen',ans4:'Ctrl+PrintScreen'},
{ans:1,que:'Windows XP 要截取「整個螢幕」成為一個圖案時，則應按那一組按鍵？',ans1:'PrintScreen',ans2:'Shift+PrintScreen',ans3:'Alt+PrintScreen',ans4:'Ctrl+PrintScreen'},
{ans:1,que:'關於Windows XP 正常關機程式之敘述何者較佳？',ans1:'必須由「開始功能表」選關機',ans2:'可以由「工作管理員」選關機',ans3:'可以由系統的「啟動/關機」選關機',ans4:'可以直接關電源'},
{ans:3,que:'Windows XP 要執行「開始/關機/登出」的選項，則會執行那一個動作？',ans1:'關閉Windows XP',ans2:'重新啟動Windows XP',ans3:'可以讓新的使用者登入',ans4:'讓電腦運作暫停，並可以省電'},
{ans:3,que:'Windows XP 內的「媒體播放程式{ans:Windows Media Player)」，無法播放那一種格式的檔案？',ans1:'音樂CD',ans2:'AVI',ans3:'jpg',ans4:'Wave 音效'},
{ans:2,que:'關於Windows XP 檔案與資料夾設定，何者為正確？',ans1:'檔案可共用，資料夾可共用',ans2:'檔案不可共用，資料夾可共用',ans3:'檔案可共用，資料夾不可共用',ans4:'檔案不可共用，資料夾不可共用'},
{ans:2,que:'Windows XP 要切換不同的「中文輸入法」，其預設值為按下那一組按鍵？',ans1:'Ctrl+Alt',ans2:'Ctrl+Shift',ans3:'Ctrl+Space',ans4:'Shift+Space'},
{ans:3,que:'Windows XP 要開啟和關閉「中文輸入法」，其預設值為按下那一組按鍵？',ans1:'Ctrl+Alt',ans2:'Ctrl+Shift',ans3:'Ctrl+Space',ans4:'Shift+Space'},
{ans:2,que:'Windows XP 的「控制台/系統/硬體/裝置管理員」中，若此時有裝置未安裝驅動程式的話，則會在該裝置前面顯示什麼符號？',ans1:'？',ans2:'！',ans3:'╳',ans4:'＄'},
{ans:4,que:'Windows XP 設定「超過20 分鐘未使用電腦」時，要自動關閉監視器，可以在「控制台」下那一個功能選項設定？',ans1:'系統',ans2:'協助工具選項',ans3:'使用者',ans4:'電源選項'},
{ans:2,que:'Windows XP 要「移除一個硬體的設定值」，則應在「控制台」下那一個選項執行？',ans1:'新增/移除程式',ans2:'系統',ans3:'使用者',ans4:'加入新的硬體'},
{ans:1,que:'何者不是Windows XP「磁碟重組程式」的目的？',ans1:'重組目錄',ans2:'重組檔案',ans3:'重組可用空間',ans4:'同時重組檔案及可用空間'},
{ans:4,que:'Windows XP 的「網路上的芳鄰」無法搜尋到何者？',ans1:'區域網路上的其他電腦',ans2:'區域網路上的其他伺服器',ans3:'區域網路上的其他印表機',ans4:'區域網路上的數據機'},
{ans:2,que:'Windows XP 的「網路上的芳鄰」若要顯示本機的電腦名稱為「HAPPY」，則應該在「控制台/系統」下那一功能選項去設定？',ans1:'電腦說明',ans2:'電腦名稱',ans3:'組態',ans4:'工作群組'},
{ans:1,que:'Windows 7 的「電腦」中，若先選取C 磁碟中的一個資料夾，再將之拖曳至D 磁碟中，則其執行的動作為何？',ans1:'複製',ans2:'搬移',ans3:'刪除',ans4:'剪下'},
{ans:3,que:'Windows 7 的「電腦」中，若先選取某一個檔案後，再選取「傳送到」的「3.5 磁片{ans:A:)」選項，則其執行的動作為何？',ans1:'在A 磁碟機中建立一個指到該檔案的捷徑',ans2:'將該檔案由A 磁碟複製到硬碟內',ans3:'將該檔案複製到A磁碟',ans4:'將該檔案搬移到A 磁碟'},
{ans:1,que:'Windows 7 的「電腦」中，若在執行刪除一個檔案時，不想讓該檔案被移至「資源回收筒」內，則刪除時應先按下那一個鍵？',ans1:'Shift',ans2:'Ctrl＋Alt',ans3:'Alt',ans4:'Ctrl'},
{ans:2,que:'Windows 7 的「電腦」中，若要選取全部檔案，則在選取檔案前，應先配合按住那一組按鍵？',ans1:'Shift+A',ans2:'Ctrl+A',ans3:'Shift',ans4:'Ctrl'},
{ans:4,que:'Windows 7 的「電腦」中，若要顯示檔案名稱的副檔名，則應在那一個功能表的選項下設定之？',ans1:'開啟控制台/組合管理/檢視',ans2:'開啟控制台/系統內容/檢視',ans3:'開啟控制台/系統及安全/檢視',ans4:'開啟控制台/外觀及個人化/資料夾選項/檢視'},
{ans:1,que:'Windows 7 的「電腦」中，若選取C：磁碟中的檔案，按住Ctrl + Shit 鍵後並拖曳至桌面上，則會進行哪一個動作？',ans1:'在桌面上建立一個該檔案的捷徑',ans2:'在桌面上顯示該檔案的內容',ans3:'將該檔案刪除',ans4:'此動作不被允許'},
{ans:3,que:'Windows XP 登入時，若鍵入的密碼其「大小寫不正確」會導致什麼結果？',ans1:'仍可以進入Windows XP',ans2:'進入Windows XP 的安全模式',ans3:'要求重新輸入密碼',ans4:'Windows XP 將先關閉，並重新開機'},
{ans:1,que:'使用Windows XP 的「電話和數據機選項」接上Internet，則必須安裝設定那一種網路通訊協定？',ans1:'TCP/IP',ans2:'PPP',ans3:'NetBEUI',ans4:'IPX/SPX'},
{ans:4,que:'Windows XP 的「檔案總管」要檢視檔案的「修改日期」，應使用那一個選項的模式？',ans1:'清單',ans2:'小圖示',ans3:'大圖示',ans4:'詳細資料'},
{ans:2,que:'Windows XP 執行「複製及刪除檔案」的動作，則應定期執行何種程式，以讓硬碟空間剩餘區塊可呈現更連續？',ans1:'磁碟掃瞄程式',ans2:'磁碟重組程式',ans3:'磁碟壓縮程式',ans4:'病毒掃瞄程式'},
{ans:1,que:'Windows XP 要觀察安裝軟體的記錄，可以查看那一個記錄檔的內容？',ans1:'setuplog.txt',ans2:'netlog.txt',ans3:'detlog.txt',ans4:'winlog.txt'},
{ans:1,que:'Windows XP 的桌面上按滑鼠右鍵，並選「內容」選項，則會開啟「控制台」的那一個選項？',ans1:'顯示',ans2:'字型',ans3:'網路和撥號連線',ans4:'系統'},
{ans:4,que:'Windows XP 所提供的何項功能可以檢查長檔名？',ans1:'字元對應表',ans2:'系統資訊',ans3:'系統還原',ans4:'磁碟掃瞄工具'},
{ans:4,que:'Windows XP 要將某一資料夾與在網路上的使用者分享使用，可先在該資料夾的圖示下按滑鼠右鍵一下，再選擇「快顯功能表」中的何項功能即可完成？',ans1:'開啟',ans2:'檔案總管',ans3:'搜尋',ans4:'共用和安全性'},
{ans:4,que:'Windows 7 要移除Microsoft Office 應用軟體程式，可利用「控制台」中的何項功能即可完成？',ans1:'外觀和主題',ans2:'印表機和其他硬體',ans3:'新增/移除程式',ans4:'程式集/解除安裝程式'},
{ans:1,que:'Windows XP 將「滑鼠」設定成「慣用左手」後，則按幾下滑鼠左鍵將會顯示快顯功能表？',ans1:'一下',ans2:'兩下',ans3:'三下',ans4:'四下'},
{ans:4,que:'Windows XP 中的何項功能是為保持與拷貝到磁碟片的連結關係，用以確保檔案是在最新的狀態？',ans1:'記事本',ans2:'小畫家',ans3:'我的文件',ans4:'公事包'},
{ans:1,que:'Windows XP 的「桌面」要刪除某一捷徑，可先移到「捷徑圖示」處按滑鼠何處幾下，再按Delete 鍵，出現「確認刪除捷徑」對話方塊時，選擇「刪除捷徑」即可？',ans1:'左鍵一下',ans2:'左鍵兩下',ans3:'右鍵一下',ans4:'右鍵兩下'},
{ans:4,que:'Windows XP「控制台」中的何項功能，可用以「新增/移除」某一種中文輸入法？',ans1:'系統',ans2:'印表機和傳真',ans3:'鍵盤',ans4:'地區及語言選項'},
{ans:2,que:'Windows XP「控制台」的何項功能，可用以執行「新增印表機」的動作？',ans1:'系統',ans2:'印表機和傳真',ans3:'鍵盤',ans4:'地區及語言選項'},
{ans:1,que:'Windows XP「檔案總管」若某一資料夾的前方有出現何種符號時，表示其內尚包含有下一層的資料夾？',ans1:'＋',ans2:'-',ans3:'*',ans4:'/'},
{ans:4,que:'Windows XP「檔案總管」若要以滑鼠選取多個連續的檔案，可先以滑鼠點取要選的第一個檔案，然後按住何項功能鍵後，再以滑鼠選取最後一個檔案即可？',ans1:'Ctrl',ans2:'Enter',ans3:'Ctrl+Shift',ans4:'Shift'},
{ans:4,que:'Windows XP「檔案總管」若要將某一資料夾內的檔案全部選取，可先按「編輯」、再選何項功能即可？',ans1:'複製',ans2:'剪下',ans3:'反向選擇',ans4:'全選'},
{ans:3,que:'Windows XP「檔案總管」若要選擇大部分的檔案，可先選取不需要的少數檔案，再按「編輯」的何項功能即可？',ans1:'複製',ans2:'剪下',ans3:'反向選擇',ans4:'全選'},
{ans:4,que:'Windows XP「檔案總管」若欲「列印」某一檔案的內容時，可將該檔案選取後，再直接拖曳至何項功能的圖示內即可？',ans1:'我的文件',ans2:'我的電腦',ans3:'網路芳鄰',ans4:'印表機'},
{ans:3,que:'Windows XP「檔案總管」若欲改變某一個檔案的屬性，可先選取該檔案後，再按右鍵一下，然後由「快顯功能表」的何項功能下進行更改之？',ans1:'編輯',ans2:'剪下',ans3:'內容',ans4:'貼上'},
{ans:4,que:'Windows XP「檔案總管」若欲搜尋某一檔案時，可先按何項功能鈕一下，再由「所有檔案和資料夾」對話方塊輸入待搜尋的檔案名稱即可？',ans1:'檢視',ans2:'資料夾',ans3:'上移',ans4:'搜尋'},
{ans:4,que:'Windows XP 要更改桌面圖示的名稱，只需先在該圖示上按滑鼠右鍵一下，再點選何項功能，即可鍵入、並更改其名稱？',ans1:'剪下',ans2:'複製',ans3:'刪除',ans4:'重新命名'},
{ans:1,que:'若在工作列上顯示有數個應用程式已經被開啟，此時可以利用何種鍵盤的操作，就可以在各個不同程式的工作視窗間任意的切換？',ans1:'Alt＋Tab',ans2:'Shift＋Tab',ans3:'Ctrl＋Tab',ans4:'Ctrl＋Shift'},
{ans:1,que:'安裝Windows XP 後，系統內建何種程式可以讓使用者透過Internet 或Intranet 進行視訊會議？',ans1:'NetMeeting',ans2:'WordPad',ans3:'Windows Picture and Fax Viewer',ans4:'Windows Movie Maker'},
{ans:2,que:'Windows XP 作為本機測試用的IP 位址為何？',ans1:'168.56.8.13',ans2:'127.0.0.1',ans3:'192.1.1.1',ans4:'255.255.255.0'},
{ans:1,que:'Windows XP 作業系統安裝網站伺服器IIS 後，使用網站不可或缺的通訊協定為何？',ans1:'TCP/IP',ans2:'Gopher',ans3:'NetBEUI',ans4:'PPP'},
{ans:3,que:'除了使用網頁製作軟體外，使用者也可以使用Windows XP 附屬應用程式中的何者來編輯網頁？',ans1:'小畫家',ans2:'命令提示字元',ans3:'記事本',ans4:'Windows 檔案總管'},
{ans:3,que:'Windows XP Professional 的指令，何者可以查詢目前系統的配接卡位址及IP 位址？',ans1:'ping',ans2:'config',ans3:'ipconfig',ans4:'netstat'},
{ans:1,que:'何者是Windows Server 2003 作業系統「系統管理者」的預設帳號？',ans1:'administrator',ans2:'manager',ans3:'root',ans4:'supervisor'},
{ans:3,que:'Windows Server 2000 所使用True Type 字型的檔案副檔名為何？',ans1:'.exe',ans2:'.ini',ans3:'.ttf',ans4:'.fon'},
{ans:3,que:'若將Windows Server 2003 當成伺服器時，則要觀察有那些使用者登入的話，可以使用何者予以監視？',ans1:'管理精靈',ans2:'工作管理員',ans3:'伺服器管理員',ans4:'使用者管理員'},
{ans:1,que:'"Linux"是屬於那類軟體？',ans1:'系統軟體',ans2:'文書編輯軟體',ans3:'簡報軟體',ans4:'資料庫軟體'},
{ans:1,que:'"Windows Server 2003"是屬於那類軟體？',ans1:'系統軟體',ans2:'文書編輯軟體',ans3:'簡報軟體',ans4:'資料庫軟體'},
{ans:1,que:'"UNIX"是屬於那類軟體？',ans1:'系統軟體',ans2:'文書編輯軟體',ans3:'簡報軟體',ans4:'資料庫軟體'},
{ans:1,que:'"Windows Vista"是屬於那類軟體？',ans1:'系統軟體',ans2:'文書編輯軟體',ans3:'簡報軟體',ans4:'資料庫軟體'},
{ans:3,que:'對於Linux 作業系統發行版，何者為非？',ans1:'Fedora Core',ans2:'Red Hat',ans3:'BSD',ans4:'SUSE'},
{ans:2,que:'對於Unix 作業系統的特色，何者敘述有誤？',ans1:'移植性高',ans2:'功能強大完整的作業系統',ans3:'多人多工',ans4:'具可靠的安全性'},
{ans:2,que:'何者最不適合擔任網路作業系統？',ans1:'Windows Server 2008',ans2:'Windows Vista',ans3:'Unix',ans4:'Linux'},
{ans:3,que:'Windows Vista 作業系統的UAC 功能為何？',ans1:'高度安全的防火牆技術',ans2:'高效能的搜尋技術',ans3:'獨特的帳戶控制技術',ans4:'全新的瀏覽技術'},
{ans:2,que:'Windows Vista 作業系統欲進行系統備份，磁碟至少要具備多少MB 空間才能進行備份？',ans1:'200',ans2:'300',ans3:'400',ans4:'500'},
{ans:1,que:'在Linux 作業系統下，若遇到不知其義的指令，可透過那一指令查詢？',ans1:'man',ans2:'cd',ans3:'ls',ans4:'pwd'},
{ans:4,que:'在Linux 作業系統下，若想偵測某個網站或所在的網路環境是否正常運作，可透過那一指令測試？',ans1:'ftp',ans2:'get',ans3:'bye',ans4:'ping'},
{ans:1,que:'在Linux 作業系統文字模式下，欲進行文書編輯工作可採用那一個編輯軟體？',ans1:'nano',ans2:'WordPad',ans3:'PE2',ans4:'Notepad'},
{ans:2,que:'Mac OS 作業系統的檔案夾視窗稱呼為何？',ans1:'Folder',ans2:'Finder',ans3:'Icon',ans4:'Dock'},
{ans:4,que:'欲在Mac OS 作業系統下執行應用程式，最快的途徑是在何者中按一下欲執行程式的替身影像？',ans1:'Core',ans2:'Finder',ans3:'Folder',ans4:'Dock'},
{ans:4,que:'關於個人電腦記憶體之敘述，何者錯誤？',ans1:'ROM 常用來存放系統程式',ans2:'軟碟與硬碟屬於輔助記憶體',ans3:'電腦關機後，RAM 內部的資料會消失',ans4:'ROM 中的資料只能被存入，不能讀出'},
{ans:4,que:'電腦開機啟動BIOS 後，接著會執行何種軟體？',ans1:'防毒軟體',ans2:'壓縮軟體',ans3:'應用軟體',ans4:'作業系統'},
{ans:4,que:'電腦五大單元中，負責電腦系統之指揮及控制的為何？',ans1:'記憶單元',ans2:'輸出入單元',ans3:'算數/邏輯單元',ans4:'控制單元'},
{ans:1,que:'那種高階電腦語言較適合發展系統程式？',ans1:'C++',ans2:'Basic',ans3:'Fortran',ans4:'LISP'},
{ans:1,que:'電腦開機啟動時，何者為其最優先啟動順序？',ans1:'基本輸出入系統',ans2:'作業系統',ans3:'應用程式系統',ans4:'網路系統'},
{ans:4,que:'假設B=5，C=10 計算A=B+C 時，控制單元會到那裡取出代表B 位址、C 位址的值送到ALU 相加？',ans1:'輸入單元',ans2:'輸出單元',ans3:'中央處理單元',ans4:'記憶體'},
{ans:2,que:'ALU 運算之結果，可直接送至何處？',ans1:'Monitor',ans2:'CPU 內之Register',ans3:'Printer',ans4:'ROM'},
{ans:4,que:'早期傳統的基本輸入輸出系統{ans:Base Input Output System)通常儲存於何種記憶體中？',ans1:'軟碟',ans2:'硬碟',ans3:'RAM',ans4:'ROM'},
{ans:2,que:'CPU 必須先將要存取的位址存入何處才能到主記憶體中存取資料？',ans1:'資料暫存器',ans2:'位址暫存器',ans3:'指令暫存器',ans4:'輸出暫存器'},
{ans:1,que:'關於個人電腦PC 有256MB 主記憶體之敘述何者正確？',ans1:'256×1024KB RAM',ans2:'256×1024bytes RAM',ans3:'256×1024KBROM',ans4:'256×1024bytes ROM'},
{ans:1,que:'何種技術是利用輔助記憶體{ans:例如硬碟)模擬主記憶體，以使記憶體之空間變大，提供使用者的電腦來使用？',ans1:'虛擬記憶體',ans2:'快取記憶體',ans3:'隨機記憶體',ans4:'唯讀記憶體'},
{ans:4,que:'電腦最基本的運算方式為何？',ans1:'乘法',ans2:'除法',ans3:'減法',ans4:'加法'},
{ans:2,que:'標明Pentium Ⅳ 3.0G 之CPU，其中3.0G 指的為何？',ans1:'主記憶體空間可擴充之範圍',ans2:'該CPU 可接受之時脈頻率',ans3:'該CPU 之製造序號及批號',ans4:'CPU 之位元數'},
{ans:2,que:'關於軟體之敘述何者正確？',ans1:'編譯器{ans:Compiler)可編譯應用程式，應屬於應用軟體',ans2:'會計系統可輔助會計作業，應屬於應用軟體',ans3:'作業系統不能編譯程式，故不屬於系統軟體',ans4:'作業系統{ans:Operation System)可編譯程式，應屬於系統軟體'},
{ans:1,que:'256 色的圖片中，每個像素都使用多少的空間？',ans1:'8bits',ans2:'8bytes',ans3:'256bits',ans4:'256bytes'},
{ans:3,que:'協助使用者能更簡易、有效率的使用電腦系統的為何？',ans1:'程式設計軟體',ans2:'工具軟體',ans3:'系統軟體',ans4:'應用軟體'},
{ans:3,que:'何者非程式語言所能開啟的檔案？',ans1:'循序檔',ans2:'隨機檔',ans3:'交易檔',ans4:'二進位檔'},
{ans:2,que:'何種電腦語言不必經過解譯即可由電腦直接執行？',ans1:'組合語言',ans2:'機器語言',ans3:'BASIC 語言',ans4:'C 語言'},
{ans:1,que:'何者為物件導向程式語言？',ans1:'Java',ans2:'QBasic',ans3:'PASCAL',ans4:'C'},
{ans:2,que:'高階語言所寫的程式都必須翻譯成何種碼後，電腦才能執行？',ans1:'目的碼',ans2:'機器碼',ans3:'連結程式',ans4:'組合語言'},
{ans:1,que:'何種語言程式比較容易維護？',ans1:'高階語言程式',ans2:'機器語言程式',ans3:'I/O 語言程式',ans4:'組合語言程式'},
{ans:1,que:'測試自己電腦的網路卡是否正常，可執行那一個指令？',ans1:'PING 127.0.0.1',ans2:'TRACERT 127.0.0.1',ans3:'TELNET 127.0.0.1',ans4:'FTP 127.0.0.1'},
{ans:1,que:'在Internet Explorer 中選按那一個選項，可以設定開啟瀏覽器時的首頁?',ans1:'『工具/Internet 選項』',ans2:'『檔案/開啟舊檔』',ans3:'『檢視/重新整理』',ans4:'『檔案/版面設定』'},
{ans:2,que:'Internet Explorer 6 要同時瀏覽二個以上的網站，可執行那個動作？',ans1:'「檔案/開啟舊檔」',ans2:'「檔案/新增/視窗」',ans3:'「檢視/原始檔」',ans4:'「檢視/全螢幕」'},
{ans:3,que:'關於UNIX 作業系統之敘述何者錯誤？',ans1:'是一種多人多工的作業系統',ans2:'檔案結構為階層式的結構{ans:hierarchical structure)',ans3:'系統的可攜性{ans:portability)不佳',ans4:'UNIX Shell 是使用者與系統溝通的橋樑'},
{ans:2,que:'何種作業系統不具備視窗{ans:Window)環境？',ans1:'UNIX',ans2:'DOS',ans3:'OS/2',ans4:'MS-Windows'},
{ans:3,que:'將類似資料收集起來於固定時間一起處理的作業方式稱之為何？',ans1:'連線處理',ans2:'即時處理',ans3:'批次處理',ans4:'分時處理'}]